%%{
	machine entities;
	
	parse_entity := (
				"Aacute;" @{append_codepoint(193);} |
				"aacute;" @{append_codepoint(225);} |
				"Abreve;" @{append_codepoint(258);} |
				"abreve;" @{append_codepoint(259);} |
				"ac;" @{append_codepoint(8766);} |
				"acd;" @{append_codepoint(8767);} |
				"acE;" @{append_codepoint(8766);append_codepoint(819);} |
				"Acirc;" @{append_codepoint(194);} |
				"acirc;" @{append_codepoint(226);} |
				"acute;" @{append_codepoint(180);} |
				"Acy;" @{append_codepoint(1040);} |
				"acy;" @{append_codepoint(1072);} |
				"AElig;" @{append_codepoint(198);} |
				"aelig;" @{append_codepoint(230);} |
				"af;" @{append_codepoint(8289);} |
				"Afr;" @{append_codepoint(120068);} |
				"afr;" @{append_codepoint(120094);} |
				"Agrave;" @{append_codepoint(192);} |
				"agrave;" @{append_codepoint(224);} |
				"alefsym;" @{append_codepoint(8501);} |
				"aleph;" @{append_codepoint(8501);} |
				"Alpha;" @{append_codepoint(913);} |
				"alpha;" @{append_codepoint(945);} |
				"Amacr;" @{append_codepoint(256);} |
				"amacr;" @{append_codepoint(257);} |
				"amalg;" @{append_codepoint(10815);} |
				"AMP;" @{append_codepoint(38);} |
				"amp;" @{append_codepoint(38);} |
				"And;" @{append_codepoint(10835);} |
				"and;" @{append_codepoint(8743);} |
				"andand;" @{append_codepoint(10837);} |
				"andd;" @{append_codepoint(10844);} |
				"andslope;" @{append_codepoint(10840);} |
				"andv;" @{append_codepoint(10842);} |
				"ang;" @{append_codepoint(8736);} |
				"ange;" @{append_codepoint(10660);} |
				"angle;" @{append_codepoint(8736);} |
				"angmsd;" @{append_codepoint(8737);} |
				"angmsdaa;" @{append_codepoint(10664);} |
				"angmsdab;" @{append_codepoint(10665);} |
				"angmsdac;" @{append_codepoint(10666);} |
				"angmsdad;" @{append_codepoint(10667);} |
				"angmsdae;" @{append_codepoint(10668);} |
				"angmsdaf;" @{append_codepoint(10669);} |
				"angmsdag;" @{append_codepoint(10670);} |
				"angmsdah;" @{append_codepoint(10671);} |
				"angrt;" @{append_codepoint(8735);} |
				"angrtvb;" @{append_codepoint(8894);} |
				"angrtvbd;" @{append_codepoint(10653);} |
				"angsph;" @{append_codepoint(8738);} |
				"angst;" @{append_codepoint(197);} |
				"angzarr;" @{append_codepoint(9084);} |
				"Aogon;" @{append_codepoint(260);} |
				"aogon;" @{append_codepoint(261);} |
				"Aopf;" @{append_codepoint(120120);} |
				"aopf;" @{append_codepoint(120146);} |
				"ap;" @{append_codepoint(8776);} |
				"apacir;" @{append_codepoint(10863);} |
				"apE;" @{append_codepoint(10864);} |
				"ape;" @{append_codepoint(8778);} |
				"apid;" @{append_codepoint(8779);} |
				"apos;" @{append_codepoint(39);} |
				"ApplyFunction;" @{append_codepoint(8289);} |
				"approx;" @{append_codepoint(8776);} |
				"approxeq;" @{append_codepoint(8778);} |
				"Aring;" @{append_codepoint(197);} |
				"aring;" @{append_codepoint(229);} |
				"Ascr;" @{append_codepoint(119964);} |
				"ascr;" @{append_codepoint(119990);} |
				"Assign;" @{append_codepoint(8788);} |
				"ast;" @{append_codepoint(42);} |
				"asymp;" @{append_codepoint(8776);} |
				"asympeq;" @{append_codepoint(8781);} |
				"Atilde;" @{append_codepoint(195);} |
				"atilde;" @{append_codepoint(227);} |
				"Auml;" @{append_codepoint(196);} |
				"auml;" @{append_codepoint(228);} |
				"awconint;" @{append_codepoint(8755);} |
				"awint;" @{append_codepoint(10769);} |
				"backcong;" @{append_codepoint(8780);} |
				"backepsilon;" @{append_codepoint(1014);} |
				"backprime;" @{append_codepoint(8245);} |
				"backsim;" @{append_codepoint(8765);} |
				"backsimeq;" @{append_codepoint(8909);} |
				"Backslash;" @{append_codepoint(8726);} |
				"Barv;" @{append_codepoint(10983);} |
				"barvee;" @{append_codepoint(8893);} |
				"Barwed;" @{append_codepoint(8966);} |
				"barwed;" @{append_codepoint(8965);} |
				"barwedge;" @{append_codepoint(8965);} |
				"bbrk;" @{append_codepoint(9141);} |
				"bbrktbrk;" @{append_codepoint(9142);} |
				"bcong;" @{append_codepoint(8780);} |
				"Bcy;" @{append_codepoint(1041);} |
				"bcy;" @{append_codepoint(1073);} |
				"bdquo;" @{append_codepoint(8222);} |
				"becaus;" @{append_codepoint(8757);} |
				"Because;" @{append_codepoint(8757);} |
				"because;" @{append_codepoint(8757);} |
				"bemptyv;" @{append_codepoint(10672);} |
				"bepsi;" @{append_codepoint(1014);} |
				"bernou;" @{append_codepoint(8492);} |
				"Bernoullis;" @{append_codepoint(8492);} |
				"Beta;" @{append_codepoint(914);} |
				"beta;" @{append_codepoint(946);} |
				"beth;" @{append_codepoint(8502);} |
				"between;" @{append_codepoint(8812);} |
				"Bfr;" @{append_codepoint(120069);} |
				"bfr;" @{append_codepoint(120095);} |
				"bigcap;" @{append_codepoint(8898);} |
				"bigcirc;" @{append_codepoint(9711);} |
				"bigcup;" @{append_codepoint(8899);} |
				"bigodot;" @{append_codepoint(10752);} |
				"bigoplus;" @{append_codepoint(10753);} |
				"bigotimes;" @{append_codepoint(10754);} |
				"bigsqcup;" @{append_codepoint(10758);} |
				"bigstar;" @{append_codepoint(9733);} |
				"bigtriangledown;" @{append_codepoint(9661);} |
				"bigtriangleup;" @{append_codepoint(9651);} |
				"biguplus;" @{append_codepoint(10756);} |
				"bigvee;" @{append_codepoint(8897);} |
				"bigwedge;" @{append_codepoint(8896);} |
				"bkarow;" @{append_codepoint(10509);} |
				"blacklozenge;" @{append_codepoint(10731);} |
				"blacksquare;" @{append_codepoint(9642);} |
				"blacktriangle;" @{append_codepoint(9652);} |
				"blacktriangledown;" @{append_codepoint(9662);} |
				"blacktriangleleft;" @{append_codepoint(9666);} |
				"blacktriangleright;" @{append_codepoint(9656);} |
				"blank;" @{append_codepoint(9251);} |
				"blk12;" @{append_codepoint(9618);} |
				"blk14;" @{append_codepoint(9617);} |
				"blk34;" @{append_codepoint(9619);} |
				"block;" @{append_codepoint(9608);} |
				"bne;" @{append_codepoint(61);append_codepoint(8421);} |
				"bnequiv;" @{append_codepoint(8801);append_codepoint(8421);} |
				"bNot;" @{append_codepoint(10989);} |
				"bnot;" @{append_codepoint(8976);} |
				"Bopf;" @{append_codepoint(120121);} |
				"bopf;" @{append_codepoint(120147);} |
				"bot;" @{append_codepoint(8869);} |
				"bottom;" @{append_codepoint(8869);} |
				"bowtie;" @{append_codepoint(8904);} |
				"boxbox;" @{append_codepoint(10697);} |
				"boxDL;" @{append_codepoint(9559);} |
				"boxDl;" @{append_codepoint(9558);} |
				"boxdL;" @{append_codepoint(9557);} |
				"boxdl;" @{append_codepoint(9488);} |
				"boxDR;" @{append_codepoint(9556);} |
				"boxDr;" @{append_codepoint(9555);} |
				"boxdR;" @{append_codepoint(9554);} |
				"boxdr;" @{append_codepoint(9484);} |
				"boxH;" @{append_codepoint(9552);} |
				"boxh;" @{append_codepoint(9472);} |
				"boxHD;" @{append_codepoint(9574);} |
				"boxHd;" @{append_codepoint(9572);} |
				"boxhD;" @{append_codepoint(9573);} |
				"boxhd;" @{append_codepoint(9516);} |
				"boxHU;" @{append_codepoint(9577);} |
				"boxHu;" @{append_codepoint(9575);} |
				"boxhU;" @{append_codepoint(9576);} |
				"boxhu;" @{append_codepoint(9524);} |
				"boxminus;" @{append_codepoint(8863);} |
				"boxplus;" @{append_codepoint(8862);} |
				"boxtimes;" @{append_codepoint(8864);} |
				"boxUL;" @{append_codepoint(9565);} |
				"boxUl;" @{append_codepoint(9564);} |
				"boxuL;" @{append_codepoint(9563);} |
				"boxul;" @{append_codepoint(9496);} |
				"boxUR;" @{append_codepoint(9562);} |
				"boxUr;" @{append_codepoint(9561);} |
				"boxuR;" @{append_codepoint(9560);} |
				"boxur;" @{append_codepoint(9492);} |
				"boxV;" @{append_codepoint(9553);} |
				"boxv;" @{append_codepoint(9474);} |
				"boxVH;" @{append_codepoint(9580);} |
				"boxVh;" @{append_codepoint(9579);} |
				"boxvH;" @{append_codepoint(9578);} |
				"boxvh;" @{append_codepoint(9532);} |
				"boxVL;" @{append_codepoint(9571);} |
				"boxVl;" @{append_codepoint(9570);} |
				"boxvL;" @{append_codepoint(9569);} |
				"boxvl;" @{append_codepoint(9508);} |
				"boxVR;" @{append_codepoint(9568);} |
				"boxVr;" @{append_codepoint(9567);} |
				"boxvR;" @{append_codepoint(9566);} |
				"boxvr;" @{append_codepoint(9500);} |
				"bprime;" @{append_codepoint(8245);} |
				"Breve;" @{append_codepoint(728);} |
				"breve;" @{append_codepoint(728);} |
				"brvbar;" @{append_codepoint(166);} |
				"Bscr;" @{append_codepoint(8492);} |
				"bscr;" @{append_codepoint(119991);} |
				"bsemi;" @{append_codepoint(8271);} |
				"bsim;" @{append_codepoint(8765);} |
				"bsime;" @{append_codepoint(8909);} |
				"bsol;" @{append_codepoint(92);} |
				"bsolb;" @{append_codepoint(10693);} |
				"bsolhsub;" @{append_codepoint(10184);} |
				"bull;" @{append_codepoint(8226);} |
				"bullet;" @{append_codepoint(8226);} |
				"bump;" @{append_codepoint(8782);} |
				"bumpE;" @{append_codepoint(10926);} |
				"bumpe;" @{append_codepoint(8783);} |
				"Bumpeq;" @{append_codepoint(8782);} |
				"bumpeq;" @{append_codepoint(8783);} |
				"Cacute;" @{append_codepoint(262);} |
				"cacute;" @{append_codepoint(263);} |
				"Cap;" @{append_codepoint(8914);} |
				"cap;" @{append_codepoint(8745);} |
				"capand;" @{append_codepoint(10820);} |
				"capbrcup;" @{append_codepoint(10825);} |
				"capcap;" @{append_codepoint(10827);} |
				"capcup;" @{append_codepoint(10823);} |
				"capdot;" @{append_codepoint(10816);} |
				"CapitalDifferentialD;" @{append_codepoint(8517);} |
				"caps;" @{append_codepoint(8745);append_codepoint(65024);} |
				"caret;" @{append_codepoint(8257);} |
				"caron;" @{append_codepoint(711);} |
				"Cayleys;" @{append_codepoint(8493);} |
				"ccaps;" @{append_codepoint(10829);} |
				"Ccaron;" @{append_codepoint(268);} |
				"ccaron;" @{append_codepoint(269);} |
				"Ccedil;" @{append_codepoint(199);} |
				"ccedil;" @{append_codepoint(231);} |
				"Ccirc;" @{append_codepoint(264);} |
				"ccirc;" @{append_codepoint(265);} |
				"Cconint;" @{append_codepoint(8752);} |
				"ccups;" @{append_codepoint(10828);} |
				"ccupssm;" @{append_codepoint(10832);} |
				"Cdot;" @{append_codepoint(266);} |
				"cdot;" @{append_codepoint(267);} |
				"cedil;" @{append_codepoint(184);} |
				"Cedilla;" @{append_codepoint(184);} |
				"cemptyv;" @{append_codepoint(10674);} |
				"cent;" @{append_codepoint(162);} |
				"CenterDot;" @{append_codepoint(183);} |
				"centerdot;" @{append_codepoint(183);} |
				"Cfr;" @{append_codepoint(8493);} |
				"cfr;" @{append_codepoint(120096);} |
				"CHcy;" @{append_codepoint(1063);} |
				"chcy;" @{append_codepoint(1095);} |
				"check;" @{append_codepoint(10003);} |
				"checkmark;" @{append_codepoint(10003);} |
				"Chi;" @{append_codepoint(935);} |
				"chi;" @{append_codepoint(967);} |
				"cir;" @{append_codepoint(9675);} |
				"circ;" @{append_codepoint(710);} |
				"circeq;" @{append_codepoint(8791);} |
				"circlearrowleft;" @{append_codepoint(8634);} |
				"circlearrowright;" @{append_codepoint(8635);} |
				"circledast;" @{append_codepoint(8859);} |
				"circledcirc;" @{append_codepoint(8858);} |
				"circleddash;" @{append_codepoint(8861);} |
				"CircleDot;" @{append_codepoint(8857);} |
				"circledR;" @{append_codepoint(174);} |
				"circledS;" @{append_codepoint(9416);} |
				"CircleMinus;" @{append_codepoint(8854);} |
				"CirclePlus;" @{append_codepoint(8853);} |
				"CircleTimes;" @{append_codepoint(8855);} |
				"cirE;" @{append_codepoint(10691);} |
				"cire;" @{append_codepoint(8791);} |
				"cirfnint;" @{append_codepoint(10768);} |
				"cirmid;" @{append_codepoint(10991);} |
				"cirscir;" @{append_codepoint(10690);} |
				"ClockwiseContourIntegral;" @{append_codepoint(8754);} |
				"CloseCurlyDoubleQuote;" @{append_codepoint(8221);} |
				"CloseCurlyQuote;" @{append_codepoint(8217);} |
				"clubs;" @{append_codepoint(9827);} |
				"clubsuit;" @{append_codepoint(9827);} |
				"Colon;" @{append_codepoint(8759);} |
				"colon;" @{append_codepoint(58);} |
				"Colone;" @{append_codepoint(10868);} |
				"colone;" @{append_codepoint(8788);} |
				"coloneq;" @{append_codepoint(8788);} |
				"comma;" @{append_codepoint(44);} |
				"commat;" @{append_codepoint(64);} |
				"comp;" @{append_codepoint(8705);} |
				"compfn;" @{append_codepoint(8728);} |
				"complement;" @{append_codepoint(8705);} |
				"complexes;" @{append_codepoint(8450);} |
				"cong;" @{append_codepoint(8773);} |
				"congdot;" @{append_codepoint(10861);} |
				"Congruent;" @{append_codepoint(8801);} |
				"Conint;" @{append_codepoint(8751);} |
				"conint;" @{append_codepoint(8750);} |
				"ContourIntegral;" @{append_codepoint(8750);} |
				"Copf;" @{append_codepoint(8450);} |
				"copf;" @{append_codepoint(120148);} |
				"coprod;" @{append_codepoint(8720);} |
				"Coproduct;" @{append_codepoint(8720);} |
				"COPY;" @{append_codepoint(169);} |
				"copy;" @{append_codepoint(169);} |
				"copysr;" @{append_codepoint(8471);} |
				"CounterClockwiseContourIntegral;" @{append_codepoint(8755);} |
				"crarr;" @{append_codepoint(8629);} |
				"Cross;" @{append_codepoint(10799);} |
				"cross;" @{append_codepoint(10007);} |
				"Cscr;" @{append_codepoint(119966);} |
				"cscr;" @{append_codepoint(119992);} |
				"csub;" @{append_codepoint(10959);} |
				"csube;" @{append_codepoint(10961);} |
				"csup;" @{append_codepoint(10960);} |
				"csupe;" @{append_codepoint(10962);} |
				"ctdot;" @{append_codepoint(8943);} |
				"cudarrl;" @{append_codepoint(10552);} |
				"cudarrr;" @{append_codepoint(10549);} |
				"cuepr;" @{append_codepoint(8926);} |
				"cuesc;" @{append_codepoint(8927);} |
				"cularr;" @{append_codepoint(8630);} |
				"cularrp;" @{append_codepoint(10557);} |
				"Cup;" @{append_codepoint(8915);} |
				"cup;" @{append_codepoint(8746);} |
				"cupbrcap;" @{append_codepoint(10824);} |
				"CupCap;" @{append_codepoint(8781);} |
				"cupcap;" @{append_codepoint(10822);} |
				"cupcup;" @{append_codepoint(10826);} |
				"cupdot;" @{append_codepoint(8845);} |
				"cupor;" @{append_codepoint(10821);} |
				"cups;" @{append_codepoint(8746);append_codepoint(65024);} |
				"curarr;" @{append_codepoint(8631);} |
				"curarrm;" @{append_codepoint(10556);} |
				"curlyeqprec;" @{append_codepoint(8926);} |
				"curlyeqsucc;" @{append_codepoint(8927);} |
				"curlyvee;" @{append_codepoint(8910);} |
				"curlywedge;" @{append_codepoint(8911);} |
				"curren;" @{append_codepoint(164);} |
				"curvearrowleft;" @{append_codepoint(8630);} |
				"curvearrowright;" @{append_codepoint(8631);} |
				"cuvee;" @{append_codepoint(8910);} |
				"cuwed;" @{append_codepoint(8911);} |
				"cwconint;" @{append_codepoint(8754);} |
				"cwint;" @{append_codepoint(8753);} |
				"cylcty;" @{append_codepoint(9005);} |
				"Dagger;" @{append_codepoint(8225);} |
				"dagger;" @{append_codepoint(8224);} |
				"daleth;" @{append_codepoint(8504);} |
				"Darr;" @{append_codepoint(8609);} |
				"dArr;" @{append_codepoint(8659);} |
				"darr;" @{append_codepoint(8595);} |
				"dash;" @{append_codepoint(8208);} |
				"Dashv;" @{append_codepoint(10980);} |
				"dashv;" @{append_codepoint(8867);} |
				"dbkarow;" @{append_codepoint(10511);} |
				"dblac;" @{append_codepoint(733);} |
				"Dcaron;" @{append_codepoint(270);} |
				"dcaron;" @{append_codepoint(271);} |
				"Dcy;" @{append_codepoint(1044);} |
				"dcy;" @{append_codepoint(1076);} |
				"DD;" @{append_codepoint(8517);} |
				"dd;" @{append_codepoint(8518);} |
				"ddagger;" @{append_codepoint(8225);} |
				"ddarr;" @{append_codepoint(8650);} |
				"DDotrahd;" @{append_codepoint(10513);} |
				"ddotseq;" @{append_codepoint(10871);} |
				"deg;" @{append_codepoint(176);} |
				"Del;" @{append_codepoint(8711);} |
				"Delta;" @{append_codepoint(916);} |
				"delta;" @{append_codepoint(948);} |
				"demptyv;" @{append_codepoint(10673);} |
				"dfisht;" @{append_codepoint(10623);} |
				"Dfr;" @{append_codepoint(120071);} |
				"dfr;" @{append_codepoint(120097);} |
				"dHar;" @{append_codepoint(10597);} |
				"dharl;" @{append_codepoint(8643);} |
				"dharr;" @{append_codepoint(8642);} |
				"DiacriticalAcute;" @{append_codepoint(180);} |
				"DiacriticalDot;" @{append_codepoint(729);} |
				"DiacriticalDoubleAcute;" @{append_codepoint(733);} |
				"DiacriticalGrave;" @{append_codepoint(96);} |
				"DiacriticalTilde;" @{append_codepoint(732);} |
				"diam;" @{append_codepoint(8900);} |
				"Diamond;" @{append_codepoint(8900);} |
				"diamond;" @{append_codepoint(8900);} |
				"diamondsuit;" @{append_codepoint(9830);} |
				"diams;" @{append_codepoint(9830);} |
				"die;" @{append_codepoint(168);} |
				"DifferentialD;" @{append_codepoint(8518);} |
				"digamma;" @{append_codepoint(989);} |
				"disin;" @{append_codepoint(8946);} |
				"div;" @{append_codepoint(247);} |
				"divide;" @{append_codepoint(247);} |
				"divideontimes;" @{append_codepoint(8903);} |
				"divonx;" @{append_codepoint(8903);} |
				"DJcy;" @{append_codepoint(1026);} |
				"djcy;" @{append_codepoint(1106);} |
				"dlcorn;" @{append_codepoint(8990);} |
				"dlcrop;" @{append_codepoint(8973);} |
				"dollar;" @{append_codepoint(36);} |
				"Dopf;" @{append_codepoint(120123);} |
				"dopf;" @{append_codepoint(120149);} |
				"Dot;" @{append_codepoint(168);} |
				"dot;" @{append_codepoint(729);} |
				"DotDot;" @{append_codepoint(8412);} |
				"doteq;" @{append_codepoint(8784);} |
				"doteqdot;" @{append_codepoint(8785);} |
				"DotEqual;" @{append_codepoint(8784);} |
				"dotminus;" @{append_codepoint(8760);} |
				"dotplus;" @{append_codepoint(8724);} |
				"dotsquare;" @{append_codepoint(8865);} |
				"doublebarwedge;" @{append_codepoint(8966);} |
				"DoubleContourIntegral;" @{append_codepoint(8751);} |
				"DoubleDot;" @{append_codepoint(168);} |
				"DoubleDownArrow;" @{append_codepoint(8659);} |
				"DoubleLeftArrow;" @{append_codepoint(8656);} |
				"DoubleLeftRightArrow;" @{append_codepoint(8660);} |
				"DoubleLeftTee;" @{append_codepoint(10980);} |
				"DoubleLongLeftArrow;" @{append_codepoint(10232);} |
				"DoubleLongLeftRightArrow;" @{append_codepoint(10234);} |
				"DoubleLongRightArrow;" @{append_codepoint(10233);} |
				"DoubleRightArrow;" @{append_codepoint(8658);} |
				"DoubleRightTee;" @{append_codepoint(8872);} |
				"DoubleUpArrow;" @{append_codepoint(8657);} |
				"DoubleUpDownArrow;" @{append_codepoint(8661);} |
				"DoubleVerticalBar;" @{append_codepoint(8741);} |
				"DownArrow;" @{append_codepoint(8595);} |
				"Downarrow;" @{append_codepoint(8659);} |
				"downarrow;" @{append_codepoint(8595);} |
				"DownArrowBar;" @{append_codepoint(10515);} |
				"DownArrowUpArrow;" @{append_codepoint(8693);} |
				"DownBreve;" @{append_codepoint(785);} |
				"downdownarrows;" @{append_codepoint(8650);} |
				"downharpoonleft;" @{append_codepoint(8643);} |
				"downharpoonright;" @{append_codepoint(8642);} |
				"DownLeftRightVector;" @{append_codepoint(10576);} |
				"DownLeftTeeVector;" @{append_codepoint(10590);} |
				"DownLeftVector;" @{append_codepoint(8637);} |
				"DownLeftVectorBar;" @{append_codepoint(10582);} |
				"DownRightTeeVector;" @{append_codepoint(10591);} |
				"DownRightVector;" @{append_codepoint(8641);} |
				"DownRightVectorBar;" @{append_codepoint(10583);} |
				"DownTee;" @{append_codepoint(8868);} |
				"DownTeeArrow;" @{append_codepoint(8615);} |
				"drbkarow;" @{append_codepoint(10512);} |
				"drcorn;" @{append_codepoint(8991);} |
				"drcrop;" @{append_codepoint(8972);} |
				"Dscr;" @{append_codepoint(119967);} |
				"dscr;" @{append_codepoint(119993);} |
				"DScy;" @{append_codepoint(1029);} |
				"dscy;" @{append_codepoint(1109);} |
				"dsol;" @{append_codepoint(10742);} |
				"Dstrok;" @{append_codepoint(272);} |
				"dstrok;" @{append_codepoint(273);} |
				"dtdot;" @{append_codepoint(8945);} |
				"dtri;" @{append_codepoint(9663);} |
				"dtrif;" @{append_codepoint(9662);} |
				"duarr;" @{append_codepoint(8693);} |
				"duhar;" @{append_codepoint(10607);} |
				"dwangle;" @{append_codepoint(10662);} |
				"DZcy;" @{append_codepoint(1039);} |
				"dzcy;" @{append_codepoint(1119);} |
				"dzigrarr;" @{append_codepoint(10239);} |
				"Eacute;" @{append_codepoint(201);} |
				"eacute;" @{append_codepoint(233);} |
				"easter;" @{append_codepoint(10862);} |
				"Ecaron;" @{append_codepoint(282);} |
				"ecaron;" @{append_codepoint(283);} |
				"ecir;" @{append_codepoint(8790);} |
				"Ecirc;" @{append_codepoint(202);} |
				"ecirc;" @{append_codepoint(234);} |
				"ecolon;" @{append_codepoint(8789);} |
				"Ecy;" @{append_codepoint(1069);} |
				"ecy;" @{append_codepoint(1101);} |
				"eDDot;" @{append_codepoint(10871);} |
				"Edot;" @{append_codepoint(278);} |
				"eDot;" @{append_codepoint(8785);} |
				"edot;" @{append_codepoint(279);} |
				"ee;" @{append_codepoint(8519);} |
				"efDot;" @{append_codepoint(8786);} |
				"Efr;" @{append_codepoint(120072);} |
				"efr;" @{append_codepoint(120098);} |
				"eg;" @{append_codepoint(10906);} |
				"Egrave;" @{append_codepoint(200);} |
				"egrave;" @{append_codepoint(232);} |
				"egs;" @{append_codepoint(10902);} |
				"egsdot;" @{append_codepoint(10904);} |
				"el;" @{append_codepoint(10905);} |
				"Element;" @{append_codepoint(8712);} |
				"elinters;" @{append_codepoint(9191);} |
				"ell;" @{append_codepoint(8467);} |
				"els;" @{append_codepoint(10901);} |
				"elsdot;" @{append_codepoint(10903);} |
				"Emacr;" @{append_codepoint(274);} |
				"emacr;" @{append_codepoint(275);} |
				"empty;" @{append_codepoint(8709);} |
				"emptyset;" @{append_codepoint(8709);} |
				"EmptySmallSquare;" @{append_codepoint(9723);} |
				"emptyv;" @{append_codepoint(8709);} |
				"EmptyVerySmallSquare;" @{append_codepoint(9643);} |
				"emsp;" @{append_codepoint(8195);} |
				"emsp13;" @{append_codepoint(8196);} |
				"emsp14;" @{append_codepoint(8197);} |
				"ENG;" @{append_codepoint(330);} |
				"eng;" @{append_codepoint(331);} |
				"ensp;" @{append_codepoint(8194);} |
				"Eogon;" @{append_codepoint(280);} |
				"eogon;" @{append_codepoint(281);} |
				"Eopf;" @{append_codepoint(120124);} |
				"eopf;" @{append_codepoint(120150);} |
				"epar;" @{append_codepoint(8917);} |
				"eparsl;" @{append_codepoint(10723);} |
				"eplus;" @{append_codepoint(10865);} |
				"epsi;" @{append_codepoint(949);} |
				"Epsilon;" @{append_codepoint(917);} |
				"epsilon;" @{append_codepoint(949);} |
				"epsiv;" @{append_codepoint(1013);} |
				"eqcirc;" @{append_codepoint(8790);} |
				"eqcolon;" @{append_codepoint(8789);} |
				"eqsim;" @{append_codepoint(8770);} |
				"eqslantgtr;" @{append_codepoint(10902);} |
				"eqslantless;" @{append_codepoint(10901);} |
				"Equal;" @{append_codepoint(10869);} |
				"equals;" @{append_codepoint(61);} |
				"EqualTilde;" @{append_codepoint(8770);} |
				"equest;" @{append_codepoint(8799);} |
				"Equilibrium;" @{append_codepoint(8652);} |
				"equiv;" @{append_codepoint(8801);} |
				"equivDD;" @{append_codepoint(10872);} |
				"eqvparsl;" @{append_codepoint(10725);} |
				"erarr;" @{append_codepoint(10609);} |
				"erDot;" @{append_codepoint(8787);} |
				"Escr;" @{append_codepoint(8496);} |
				"escr;" @{append_codepoint(8495);} |
				"esdot;" @{append_codepoint(8784);} |
				"Esim;" @{append_codepoint(10867);} |
				"esim;" @{append_codepoint(8770);} |
				"Eta;" @{append_codepoint(919);} |
				"eta;" @{append_codepoint(951);} |
				"ETH;" @{append_codepoint(208);} |
				"eth;" @{append_codepoint(240);} |
				"Euml;" @{append_codepoint(203);} |
				"euml;" @{append_codepoint(235);} |
				"euro;" @{append_codepoint(8364);} |
				"excl;" @{append_codepoint(33);} |
				"exist;" @{append_codepoint(8707);} |
				"Exists;" @{append_codepoint(8707);} |
				"expectation;" @{append_codepoint(8496);} |
				"ExponentialE;" @{append_codepoint(8519);} |
				"exponentiale;" @{append_codepoint(8519);} |
				"fallingdotseq;" @{append_codepoint(8786);} |
				"Fcy;" @{append_codepoint(1060);} |
				"fcy;" @{append_codepoint(1092);} |
				"female;" @{append_codepoint(9792);} |
				"ffilig;" @{append_codepoint(64259);} |
				"fflig;" @{append_codepoint(64256);} |
				"ffllig;" @{append_codepoint(64260);} |
				"Ffr;" @{append_codepoint(120073);} |
				"ffr;" @{append_codepoint(120099);} |
				"filig;" @{append_codepoint(64257);} |
				"FilledSmallSquare;" @{append_codepoint(9724);} |
				"FilledVerySmallSquare;" @{append_codepoint(9642);} |
				"fjlig;" @{append_codepoint(102);append_codepoint(106);} |
				"flat;" @{append_codepoint(9837);} |
				"fllig;" @{append_codepoint(64258);} |
				"fltns;" @{append_codepoint(9649);} |
				"fnof;" @{append_codepoint(402);} |
				"Fopf;" @{append_codepoint(120125);} |
				"fopf;" @{append_codepoint(120151);} |
				"ForAll;" @{append_codepoint(8704);} |
				"forall;" @{append_codepoint(8704);} |
				"fork;" @{append_codepoint(8916);} |
				"forkv;" @{append_codepoint(10969);} |
				"Fouriertrf;" @{append_codepoint(8497);} |
				"fpartint;" @{append_codepoint(10765);} |
				"frac12;" @{append_codepoint(189);} |
				"frac13;" @{append_codepoint(8531);} |
				"frac14;" @{append_codepoint(188);} |
				"frac15;" @{append_codepoint(8533);} |
				"frac16;" @{append_codepoint(8537);} |
				"frac18;" @{append_codepoint(8539);} |
				"frac23;" @{append_codepoint(8532);} |
				"frac25;" @{append_codepoint(8534);} |
				"frac34;" @{append_codepoint(190);} |
				"frac35;" @{append_codepoint(8535);} |
				"frac38;" @{append_codepoint(8540);} |
				"frac45;" @{append_codepoint(8536);} |
				"frac56;" @{append_codepoint(8538);} |
				"frac58;" @{append_codepoint(8541);} |
				"frac78;" @{append_codepoint(8542);} |
				"frasl;" @{append_codepoint(8260);} |
				"frown;" @{append_codepoint(8994);} |
				"Fscr;" @{append_codepoint(8497);} |
				"fscr;" @{append_codepoint(119995);} |
				"gacute;" @{append_codepoint(501);} |
				"Gamma;" @{append_codepoint(915);} |
				"gamma;" @{append_codepoint(947);} |
				"Gammad;" @{append_codepoint(988);} |
				"gammad;" @{append_codepoint(989);} |
				"gap;" @{append_codepoint(10886);} |
				"Gbreve;" @{append_codepoint(286);} |
				"gbreve;" @{append_codepoint(287);} |
				"Gcedil;" @{append_codepoint(290);} |
				"Gcirc;" @{append_codepoint(284);} |
				"gcirc;" @{append_codepoint(285);} |
				"Gcy;" @{append_codepoint(1043);} |
				"gcy;" @{append_codepoint(1075);} |
				"Gdot;" @{append_codepoint(288);} |
				"gdot;" @{append_codepoint(289);} |
				"gE;" @{append_codepoint(8807);} |
				"ge;" @{append_codepoint(8805);} |
				"gEl;" @{append_codepoint(10892);} |
				"gel;" @{append_codepoint(8923);} |
				"geq;" @{append_codepoint(8805);} |
				"geqq;" @{append_codepoint(8807);} |
				"geqslant;" @{append_codepoint(10878);} |
				"ges;" @{append_codepoint(10878);} |
				"gescc;" @{append_codepoint(10921);} |
				"gesdot;" @{append_codepoint(10880);} |
				"gesdoto;" @{append_codepoint(10882);} |
				"gesdotol;" @{append_codepoint(10884);} |
				"gesl;" @{append_codepoint(8923);append_codepoint(65024);} |
				"gesles;" @{append_codepoint(10900);} |
				"Gfr;" @{append_codepoint(120074);} |
				"gfr;" @{append_codepoint(120100);} |
				"Gg;" @{append_codepoint(8921);} |
				"gg;" @{append_codepoint(8811);} |
				"ggg;" @{append_codepoint(8921);} |
				"gimel;" @{append_codepoint(8503);} |
				"GJcy;" @{append_codepoint(1027);} |
				"gjcy;" @{append_codepoint(1107);} |
				"gl;" @{append_codepoint(8823);} |
				"gla;" @{append_codepoint(10917);} |
				"glE;" @{append_codepoint(10898);} |
				"glj;" @{append_codepoint(10916);} |
				"gnap;" @{append_codepoint(10890);} |
				"gnapprox;" @{append_codepoint(10890);} |
				"gnE;" @{append_codepoint(8809);} |
				"gne;" @{append_codepoint(10888);} |
				"gneq;" @{append_codepoint(10888);} |
				"gneqq;" @{append_codepoint(8809);} |
				"gnsim;" @{append_codepoint(8935);} |
				"Gopf;" @{append_codepoint(120126);} |
				"gopf;" @{append_codepoint(120152);} |
				"grave;" @{append_codepoint(96);} |
				"GreaterEqual;" @{append_codepoint(8805);} |
				"GreaterEqualLess;" @{append_codepoint(8923);} |
				"GreaterFullEqual;" @{append_codepoint(8807);} |
				"GreaterGreater;" @{append_codepoint(10914);} |
				"GreaterLess;" @{append_codepoint(8823);} |
				"GreaterSlantEqual;" @{append_codepoint(10878);} |
				"GreaterTilde;" @{append_codepoint(8819);} |
				"Gscr;" @{append_codepoint(119970);} |
				"gscr;" @{append_codepoint(8458);} |
				"gsim;" @{append_codepoint(8819);} |
				"gsime;" @{append_codepoint(10894);} |
				"gsiml;" @{append_codepoint(10896);} |
				"GT;" @{append_codepoint(62);} |
				"Gt;" @{append_codepoint(8811);} |
				"gt;" @{append_codepoint(62);} |
				"gtcc;" @{append_codepoint(10919);} |
				"gtcir;" @{append_codepoint(10874);} |
				"gtdot;" @{append_codepoint(8919);} |
				"gtlPar;" @{append_codepoint(10645);} |
				"gtquest;" @{append_codepoint(10876);} |
				"gtrapprox;" @{append_codepoint(10886);} |
				"gtrarr;" @{append_codepoint(10616);} |
				"gtrdot;" @{append_codepoint(8919);} |
				"gtreqless;" @{append_codepoint(8923);} |
				"gtreqqless;" @{append_codepoint(10892);} |
				"gtrless;" @{append_codepoint(8823);} |
				"gtrsim;" @{append_codepoint(8819);} |
				"gvertneqq;" @{append_codepoint(8809);append_codepoint(65024);} |
				"gvnE;" @{append_codepoint(8809);append_codepoint(65024);} |
				"Hacek;" @{append_codepoint(711);} |
				"hairsp;" @{append_codepoint(8202);} |
				"half;" @{append_codepoint(189);} |
				"hamilt;" @{append_codepoint(8459);} |
				"HARDcy;" @{append_codepoint(1066);} |
				"hardcy;" @{append_codepoint(1098);} |
				"hArr;" @{append_codepoint(8660);} |
				"harr;" @{append_codepoint(8596);} |
				"harrcir;" @{append_codepoint(10568);} |
				"harrw;" @{append_codepoint(8621);} |
				"Hat;" @{append_codepoint(94);} |
				"hbar;" @{append_codepoint(8463);} |
				"Hcirc;" @{append_codepoint(292);} |
				"hcirc;" @{append_codepoint(293);} |
				"hearts;" @{append_codepoint(9829);} |
				"heartsuit;" @{append_codepoint(9829);} |
				"hellip;" @{append_codepoint(8230);} |
				"hercon;" @{append_codepoint(8889);} |
				"Hfr;" @{append_codepoint(8460);} |
				"hfr;" @{append_codepoint(120101);} |
				"HilbertSpace;" @{append_codepoint(8459);} |
				"hksearow;" @{append_codepoint(10533);} |
				"hkswarow;" @{append_codepoint(10534);} |
				"hoarr;" @{append_codepoint(8703);} |
				"homtht;" @{append_codepoint(8763);} |
				"hookleftarrow;" @{append_codepoint(8617);} |
				"hookrightarrow;" @{append_codepoint(8618);} |
				"Hopf;" @{append_codepoint(8461);} |
				"hopf;" @{append_codepoint(120153);} |
				"horbar;" @{append_codepoint(8213);} |
				"HorizontalLine;" @{append_codepoint(9472);} |
				"Hscr;" @{append_codepoint(8459);} |
				"hscr;" @{append_codepoint(119997);} |
				"hslash;" @{append_codepoint(8463);} |
				"Hstrok;" @{append_codepoint(294);} |
				"hstrok;" @{append_codepoint(295);} |
				"HumpDownHump;" @{append_codepoint(8782);} |
				"HumpEqual;" @{append_codepoint(8783);} |
				"hybull;" @{append_codepoint(8259);} |
				"hyphen;" @{append_codepoint(8208);} |
				"Iacute;" @{append_codepoint(205);} |
				"iacute;" @{append_codepoint(237);} |
				"ic;" @{append_codepoint(8291);} |
				"Icirc;" @{append_codepoint(206);} |
				"icirc;" @{append_codepoint(238);} |
				"Icy;" @{append_codepoint(1048);} |
				"icy;" @{append_codepoint(1080);} |
				"Idot;" @{append_codepoint(304);} |
				"IEcy;" @{append_codepoint(1045);} |
				"iecy;" @{append_codepoint(1077);} |
				"iexcl;" @{append_codepoint(161);} |
				"iff;" @{append_codepoint(8660);} |
				"Ifr;" @{append_codepoint(8465);} |
				"ifr;" @{append_codepoint(120102);} |
				"Igrave;" @{append_codepoint(204);} |
				"igrave;" @{append_codepoint(236);} |
				"ii;" @{append_codepoint(8520);} |
				"iiiint;" @{append_codepoint(10764);} |
				"iiint;" @{append_codepoint(8749);} |
				"iinfin;" @{append_codepoint(10716);} |
				"iiota;" @{append_codepoint(8489);} |
				"IJlig;" @{append_codepoint(306);} |
				"ijlig;" @{append_codepoint(307);} |
				"Im;" @{append_codepoint(8465);} |
				"Imacr;" @{append_codepoint(298);} |
				"imacr;" @{append_codepoint(299);} |
				"image;" @{append_codepoint(8465);} |
				"ImaginaryI;" @{append_codepoint(8520);} |
				"imagline;" @{append_codepoint(8464);} |
				"imagpart;" @{append_codepoint(8465);} |
				"imath;" @{append_codepoint(305);} |
				"imof;" @{append_codepoint(8887);} |
				"imped;" @{append_codepoint(437);} |
				"Implies;" @{append_codepoint(8658);} |
				"in;" @{append_codepoint(8712);} |
				"incare;" @{append_codepoint(8453);} |
				"infin;" @{append_codepoint(8734);} |
				"infintie;" @{append_codepoint(10717);} |
				"inodot;" @{append_codepoint(305);} |
				"Int;" @{append_codepoint(8748);} |
				"int;" @{append_codepoint(8747);} |
				"intcal;" @{append_codepoint(8890);} |
				"integers;" @{append_codepoint(8484);} |
				"Integral;" @{append_codepoint(8747);} |
				"intercal;" @{append_codepoint(8890);} |
				"Intersection;" @{append_codepoint(8898);} |
				"intlarhk;" @{append_codepoint(10775);} |
				"intprod;" @{append_codepoint(10812);} |
				"InvisibleComma;" @{append_codepoint(8291);} |
				"InvisibleTimes;" @{append_codepoint(8290);} |
				"IOcy;" @{append_codepoint(1025);} |
				"iocy;" @{append_codepoint(1105);} |
				"Iogon;" @{append_codepoint(302);} |
				"iogon;" @{append_codepoint(303);} |
				"Iopf;" @{append_codepoint(120128);} |
				"iopf;" @{append_codepoint(120154);} |
				"Iota;" @{append_codepoint(921);} |
				"iota;" @{append_codepoint(953);} |
				"iprod;" @{append_codepoint(10812);} |
				"iquest;" @{append_codepoint(191);} |
				"Iscr;" @{append_codepoint(8464);} |
				"iscr;" @{append_codepoint(119998);} |
				"isin;" @{append_codepoint(8712);} |
				"isindot;" @{append_codepoint(8949);} |
				"isinE;" @{append_codepoint(8953);} |
				"isins;" @{append_codepoint(8948);} |
				"isinsv;" @{append_codepoint(8947);} |
				"isinv;" @{append_codepoint(8712);} |
				"it;" @{append_codepoint(8290);} |
				"Itilde;" @{append_codepoint(296);} |
				"itilde;" @{append_codepoint(297);} |
				"Iukcy;" @{append_codepoint(1030);} |
				"iukcy;" @{append_codepoint(1110);} |
				"Iuml;" @{append_codepoint(207);} |
				"iuml;" @{append_codepoint(239);} |
				"Jcirc;" @{append_codepoint(308);} |
				"jcirc;" @{append_codepoint(309);} |
				"Jcy;" @{append_codepoint(1049);} |
				"jcy;" @{append_codepoint(1081);} |
				"Jfr;" @{append_codepoint(120077);} |
				"jfr;" @{append_codepoint(120103);} |
				"jmath;" @{append_codepoint(567);} |
				"Jopf;" @{append_codepoint(120129);} |
				"jopf;" @{append_codepoint(120155);} |
				"Jscr;" @{append_codepoint(119973);} |
				"jscr;" @{append_codepoint(119999);} |
				"Jsercy;" @{append_codepoint(1032);} |
				"jsercy;" @{append_codepoint(1112);} |
				"Jukcy;" @{append_codepoint(1028);} |
				"jukcy;" @{append_codepoint(1108);} |
				"Kappa;" @{append_codepoint(922);} |
				"kappa;" @{append_codepoint(954);} |
				"kappav;" @{append_codepoint(1008);} |
				"Kcedil;" @{append_codepoint(310);} |
				"kcedil;" @{append_codepoint(311);} |
				"Kcy;" @{append_codepoint(1050);} |
				"kcy;" @{append_codepoint(1082);} |
				"Kfr;" @{append_codepoint(120078);} |
				"kfr;" @{append_codepoint(120104);} |
				"kgreen;" @{append_codepoint(312);} |
				"KHcy;" @{append_codepoint(1061);} |
				"khcy;" @{append_codepoint(1093);} |
				"KJcy;" @{append_codepoint(1036);} |
				"kjcy;" @{append_codepoint(1116);} |
				"Kopf;" @{append_codepoint(120130);} |
				"kopf;" @{append_codepoint(120156);} |
				"Kscr;" @{append_codepoint(119974);} |
				"kscr;" @{append_codepoint(120000);} |
				"lAarr;" @{append_codepoint(8666);} |
				"Lacute;" @{append_codepoint(313);} |
				"lacute;" @{append_codepoint(314);} |
				"laemptyv;" @{append_codepoint(10676);} |
				"lagran;" @{append_codepoint(8466);} |
				"Lambda;" @{append_codepoint(923);} |
				"lambda;" @{append_codepoint(955);} |
				"Lang;" @{append_codepoint(10218);} |
				"lang;" @{append_codepoint(10216);} |
				"langd;" @{append_codepoint(10641);} |
				"langle;" @{append_codepoint(10216);} |
				"lap;" @{append_codepoint(10885);} |
				"Laplacetrf;" @{append_codepoint(8466);} |
				"laquo;" @{append_codepoint(171);} |
				"Larr;" @{append_codepoint(8606);} |
				"lArr;" @{append_codepoint(8656);} |
				"larr;" @{append_codepoint(8592);} |
				"larrb;" @{append_codepoint(8676);} |
				"larrbfs;" @{append_codepoint(10527);} |
				"larrfs;" @{append_codepoint(10525);} |
				"larrhk;" @{append_codepoint(8617);} |
				"larrlp;" @{append_codepoint(8619);} |
				"larrpl;" @{append_codepoint(10553);} |
				"larrsim;" @{append_codepoint(10611);} |
				"larrtl;" @{append_codepoint(8610);} |
				"lat;" @{append_codepoint(10923);} |
				"lAtail;" @{append_codepoint(10523);} |
				"latail;" @{append_codepoint(10521);} |
				"late;" @{append_codepoint(10925);} |
				"lates;" @{append_codepoint(10925);append_codepoint(65024);} |
				"lBarr;" @{append_codepoint(10510);} |
				"lbarr;" @{append_codepoint(10508);} |
				"lbbrk;" @{append_codepoint(10098);} |
				"lbrace;" @{append_codepoint(123);} |
				"lbrack;" @{append_codepoint(91);} |
				"lbrke;" @{append_codepoint(10635);} |
				"lbrksld;" @{append_codepoint(10639);} |
				"lbrkslu;" @{append_codepoint(10637);} |
				"Lcaron;" @{append_codepoint(317);} |
				"lcaron;" @{append_codepoint(318);} |
				"Lcedil;" @{append_codepoint(315);} |
				"lcedil;" @{append_codepoint(316);} |
				"lceil;" @{append_codepoint(8968);} |
				"lcub;" @{append_codepoint(123);} |
				"Lcy;" @{append_codepoint(1051);} |
				"lcy;" @{append_codepoint(1083);} |
				"ldca;" @{append_codepoint(10550);} |
				"ldquo;" @{append_codepoint(8220);} |
				"ldquor;" @{append_codepoint(8222);} |
				"ldrdhar;" @{append_codepoint(10599);} |
				"ldrushar;" @{append_codepoint(10571);} |
				"ldsh;" @{append_codepoint(8626);} |
				"lE;" @{append_codepoint(8806);} |
				"le;" @{append_codepoint(8804);} |
				"LeftAngleBracket;" @{append_codepoint(10216);} |
				"LeftArrow;" @{append_codepoint(8592);} |
				"Leftarrow;" @{append_codepoint(8656);} |
				"leftarrow;" @{append_codepoint(8592);} |
				"LeftArrowBar;" @{append_codepoint(8676);} |
				"LeftArrowRightArrow;" @{append_codepoint(8646);} |
				"leftarrowtail;" @{append_codepoint(8610);} |
				"LeftCeiling;" @{append_codepoint(8968);} |
				"LeftDoubleBracket;" @{append_codepoint(10214);} |
				"LeftDownTeeVector;" @{append_codepoint(10593);} |
				"LeftDownVector;" @{append_codepoint(8643);} |
				"LeftDownVectorBar;" @{append_codepoint(10585);} |
				"LeftFloor;" @{append_codepoint(8970);} |
				"leftharpoondown;" @{append_codepoint(8637);} |
				"leftharpoonup;" @{append_codepoint(8636);} |
				"leftleftarrows;" @{append_codepoint(8647);} |
				"LeftRightArrow;" @{append_codepoint(8596);} |
				"Leftrightarrow;" @{append_codepoint(8660);} |
				"leftrightarrow;" @{append_codepoint(8596);} |
				"leftrightarrows;" @{append_codepoint(8646);} |
				"leftrightharpoons;" @{append_codepoint(8651);} |
				"leftrightsquigarrow;" @{append_codepoint(8621);} |
				"LeftRightVector;" @{append_codepoint(10574);} |
				"LeftTee;" @{append_codepoint(8867);} |
				"LeftTeeArrow;" @{append_codepoint(8612);} |
				"LeftTeeVector;" @{append_codepoint(10586);} |
				"leftthreetimes;" @{append_codepoint(8907);} |
				"LeftTriangle;" @{append_codepoint(8882);} |
				"LeftTriangleBar;" @{append_codepoint(10703);} |
				"LeftTriangleEqual;" @{append_codepoint(8884);} |
				"LeftUpDownVector;" @{append_codepoint(10577);} |
				"LeftUpTeeVector;" @{append_codepoint(10592);} |
				"LeftUpVector;" @{append_codepoint(8639);} |
				"LeftUpVectorBar;" @{append_codepoint(10584);} |
				"LeftVector;" @{append_codepoint(8636);} |
				"LeftVectorBar;" @{append_codepoint(10578);} |
				"lEg;" @{append_codepoint(10891);} |
				"leg;" @{append_codepoint(8922);} |
				"leq;" @{append_codepoint(8804);} |
				"leqq;" @{append_codepoint(8806);} |
				"leqslant;" @{append_codepoint(10877);} |
				"les;" @{append_codepoint(10877);} |
				"lescc;" @{append_codepoint(10920);} |
				"lesdot;" @{append_codepoint(10879);} |
				"lesdoto;" @{append_codepoint(10881);} |
				"lesdotor;" @{append_codepoint(10883);} |
				"lesg;" @{append_codepoint(8922);append_codepoint(65024);} |
				"lesges;" @{append_codepoint(10899);} |
				"lessapprox;" @{append_codepoint(10885);} |
				"lessdot;" @{append_codepoint(8918);} |
				"lesseqgtr;" @{append_codepoint(8922);} |
				"lesseqqgtr;" @{append_codepoint(10891);} |
				"LessEqualGreater;" @{append_codepoint(8922);} |
				"LessFullEqual;" @{append_codepoint(8806);} |
				"LessGreater;" @{append_codepoint(8822);} |
				"lessgtr;" @{append_codepoint(8822);} |
				"LessLess;" @{append_codepoint(10913);} |
				"lesssim;" @{append_codepoint(8818);} |
				"LessSlantEqual;" @{append_codepoint(10877);} |
				"LessTilde;" @{append_codepoint(8818);} |
				"lfisht;" @{append_codepoint(10620);} |
				"lfloor;" @{append_codepoint(8970);} |
				"Lfr;" @{append_codepoint(120079);} |
				"lfr;" @{append_codepoint(120105);} |
				"lg;" @{append_codepoint(8822);} |
				"lgE;" @{append_codepoint(10897);} |
				"lHar;" @{append_codepoint(10594);} |
				"lhard;" @{append_codepoint(8637);} |
				"lharu;" @{append_codepoint(8636);} |
				"lharul;" @{append_codepoint(10602);} |
				"lhblk;" @{append_codepoint(9604);} |
				"LJcy;" @{append_codepoint(1033);} |
				"ljcy;" @{append_codepoint(1113);} |
				"Ll;" @{append_codepoint(8920);} |
				"ll;" @{append_codepoint(8810);} |
				"llarr;" @{append_codepoint(8647);} |
				"llcorner;" @{append_codepoint(8990);} |
				"Lleftarrow;" @{append_codepoint(8666);} |
				"llhard;" @{append_codepoint(10603);} |
				"lltri;" @{append_codepoint(9722);} |
				"Lmidot;" @{append_codepoint(319);} |
				"lmidot;" @{append_codepoint(320);} |
				"lmoust;" @{append_codepoint(9136);} |
				"lmoustache;" @{append_codepoint(9136);} |
				"lnap;" @{append_codepoint(10889);} |
				"lnapprox;" @{append_codepoint(10889);} |
				"lnE;" @{append_codepoint(8808);} |
				"lne;" @{append_codepoint(10887);} |
				"lneq;" @{append_codepoint(10887);} |
				"lneqq;" @{append_codepoint(8808);} |
				"lnsim;" @{append_codepoint(8934);} |
				"loang;" @{append_codepoint(10220);} |
				"loarr;" @{append_codepoint(8701);} |
				"lobrk;" @{append_codepoint(10214);} |
				"LongLeftArrow;" @{append_codepoint(10229);} |
				"Longleftarrow;" @{append_codepoint(10232);} |
				"longleftarrow;" @{append_codepoint(10229);} |
				"LongLeftRightArrow;" @{append_codepoint(10231);} |
				"Longleftrightarrow;" @{append_codepoint(10234);} |
				"longleftrightarrow;" @{append_codepoint(10231);} |
				"longmapsto;" @{append_codepoint(10236);} |
				"LongRightArrow;" @{append_codepoint(10230);} |
				"Longrightarrow;" @{append_codepoint(10233);} |
				"longrightarrow;" @{append_codepoint(10230);} |
				"looparrowleft;" @{append_codepoint(8619);} |
				"looparrowright;" @{append_codepoint(8620);} |
				"lopar;" @{append_codepoint(10629);} |
				"Lopf;" @{append_codepoint(120131);} |
				"lopf;" @{append_codepoint(120157);} |
				"loplus;" @{append_codepoint(10797);} |
				"lotimes;" @{append_codepoint(10804);} |
				"lowast;" @{append_codepoint(8727);} |
				"lowbar;" @{append_codepoint(95);} |
				"LowerLeftArrow;" @{append_codepoint(8601);} |
				"LowerRightArrow;" @{append_codepoint(8600);} |
				"loz;" @{append_codepoint(9674);} |
				"lozenge;" @{append_codepoint(9674);} |
				"lozf;" @{append_codepoint(10731);} |
				"lpar;" @{append_codepoint(40);} |
				"lparlt;" @{append_codepoint(10643);} |
				"lrarr;" @{append_codepoint(8646);} |
				"lrcorner;" @{append_codepoint(8991);} |
				"lrhar;" @{append_codepoint(8651);} |
				"lrhard;" @{append_codepoint(10605);} |
				"lrm;" @{append_codepoint(8206);} |
				"lrtri;" @{append_codepoint(8895);} |
				"lsaquo;" @{append_codepoint(8249);} |
				"Lscr;" @{append_codepoint(8466);} |
				"lscr;" @{append_codepoint(120001);} |
				"Lsh;" @{append_codepoint(8624);} |
				"lsh;" @{append_codepoint(8624);} |
				"lsim;" @{append_codepoint(8818);} |
				"lsime;" @{append_codepoint(10893);} |
				"lsimg;" @{append_codepoint(10895);} |
				"lsqb;" @{append_codepoint(91);} |
				"lsquo;" @{append_codepoint(8216);} |
				"lsquor;" @{append_codepoint(8218);} |
				"Lstrok;" @{append_codepoint(321);} |
				"lstrok;" @{append_codepoint(322);} |
				"LT;" @{append_codepoint(60);} |
				"Lt;" @{append_codepoint(8810);} |
				"lt;" @{append_codepoint(60);} |
				"ltcc;" @{append_codepoint(10918);} |
				"ltcir;" @{append_codepoint(10873);} |
				"ltdot;" @{append_codepoint(8918);} |
				"lthree;" @{append_codepoint(8907);} |
				"ltimes;" @{append_codepoint(8905);} |
				"ltlarr;" @{append_codepoint(10614);} |
				"ltquest;" @{append_codepoint(10875);} |
				"ltri;" @{append_codepoint(9667);} |
				"ltrie;" @{append_codepoint(8884);} |
				"ltrif;" @{append_codepoint(9666);} |
				"ltrPar;" @{append_codepoint(10646);} |
				"lurdshar;" @{append_codepoint(10570);} |
				"luruhar;" @{append_codepoint(10598);} |
				"lvertneqq;" @{append_codepoint(8808);append_codepoint(65024);} |
				"lvnE;" @{append_codepoint(8808);append_codepoint(65024);} |
				"macr;" @{append_codepoint(175);} |
				"male;" @{append_codepoint(9794);} |
				"malt;" @{append_codepoint(10016);} |
				"maltese;" @{append_codepoint(10016);} |
				"Map;" @{append_codepoint(10501);} |
				"map;" @{append_codepoint(8614);} |
				"mapsto;" @{append_codepoint(8614);} |
				"mapstodown;" @{append_codepoint(8615);} |
				"mapstoleft;" @{append_codepoint(8612);} |
				"mapstoup;" @{append_codepoint(8613);} |
				"marker;" @{append_codepoint(9646);} |
				"mcomma;" @{append_codepoint(10793);} |
				"Mcy;" @{append_codepoint(1052);} |
				"mcy;" @{append_codepoint(1084);} |
				"mdash;" @{append_codepoint(8212);} |
				"mDDot;" @{append_codepoint(8762);} |
				"measuredangle;" @{append_codepoint(8737);} |
				"MediumSpace;" @{append_codepoint(8287);} |
				"Mellintrf;" @{append_codepoint(8499);} |
				"Mfr;" @{append_codepoint(120080);} |
				"mfr;" @{append_codepoint(120106);} |
				"mho;" @{append_codepoint(8487);} |
				"micro;" @{append_codepoint(181);} |
				"mid;" @{append_codepoint(8739);} |
				"midast;" @{append_codepoint(42);} |
				"midcir;" @{append_codepoint(10992);} |
				"middot;" @{append_codepoint(183);} |
				"minus;" @{append_codepoint(8722);} |
				"minusb;" @{append_codepoint(8863);} |
				"minusd;" @{append_codepoint(8760);} |
				"minusdu;" @{append_codepoint(10794);} |
				"MinusPlus;" @{append_codepoint(8723);} |
				"mlcp;" @{append_codepoint(10971);} |
				"mldr;" @{append_codepoint(8230);} |
				"mnplus;" @{append_codepoint(8723);} |
				"models;" @{append_codepoint(8871);} |
				"Mopf;" @{append_codepoint(120132);} |
				"mopf;" @{append_codepoint(120158);} |
				"mp;" @{append_codepoint(8723);} |
				"Mscr;" @{append_codepoint(8499);} |
				"mscr;" @{append_codepoint(120002);} |
				"mstpos;" @{append_codepoint(8766);} |
				"Mu;" @{append_codepoint(924);} |
				"mu;" @{append_codepoint(956);} |
				"multimap;" @{append_codepoint(8888);} |
				"mumap;" @{append_codepoint(8888);} |
				"nabla;" @{append_codepoint(8711);} |
				"Nacute;" @{append_codepoint(323);} |
				"nacute;" @{append_codepoint(324);} |
				"nang;" @{append_codepoint(8736);append_codepoint(8402);} |
				"nap;" @{append_codepoint(8777);} |
				"napE;" @{append_codepoint(10864);append_codepoint(824);} |
				"napid;" @{append_codepoint(8779);append_codepoint(824);} |
				"napos;" @{append_codepoint(329);} |
				"napprox;" @{append_codepoint(8777);} |
				"natur;" @{append_codepoint(9838);} |
				"natural;" @{append_codepoint(9838);} |
				"naturals;" @{append_codepoint(8469);} |
				"nbsp;" @{append_codepoint(160);} |
				"nbump;" @{append_codepoint(8782);append_codepoint(824);} |
				"nbumpe;" @{append_codepoint(8783);append_codepoint(824);} |
				"ncap;" @{append_codepoint(10819);} |
				"Ncaron;" @{append_codepoint(327);} |
				"ncaron;" @{append_codepoint(328);} |
				"Ncedil;" @{append_codepoint(325);} |
				"ncedil;" @{append_codepoint(326);} |
				"ncong;" @{append_codepoint(8775);} |
				"ncongdot;" @{append_codepoint(10861);append_codepoint(824);} |
				"ncup;" @{append_codepoint(10818);} |
				"Ncy;" @{append_codepoint(1053);} |
				"ncy;" @{append_codepoint(1085);} |
				"ndash;" @{append_codepoint(8211);} |
				"ne;" @{append_codepoint(8800);} |
				"nearhk;" @{append_codepoint(10532);} |
				"neArr;" @{append_codepoint(8663);} |
				"nearr;" @{append_codepoint(8599);} |
				"nearrow;" @{append_codepoint(8599);} |
				"nedot;" @{append_codepoint(8784);append_codepoint(824);} |
				"NegativeMediumSpace;" @{append_codepoint(8203);} |
				"NegativeThickSpace;" @{append_codepoint(8203);} |
				"NegativeThinSpace;" @{append_codepoint(8203);} |
				"NegativeVeryThinSpace;" @{append_codepoint(8203);} |
				"nequiv;" @{append_codepoint(8802);} |
				"nesear;" @{append_codepoint(10536);} |
				"nesim;" @{append_codepoint(8770);append_codepoint(824);} |
				"NestedGreaterGreater;" @{append_codepoint(8811);} |
				"NestedLessLess;" @{append_codepoint(8810);} |
				"NewLine;" @{append_codepoint(10);} |
				"nexist;" @{append_codepoint(8708);} |
				"nexists;" @{append_codepoint(8708);} |
				"Nfr;" @{append_codepoint(120081);} |
				"nfr;" @{append_codepoint(120107);} |
				"ngE;" @{append_codepoint(8807);append_codepoint(824);} |
				"nge;" @{append_codepoint(8817);} |
				"ngeq;" @{append_codepoint(8817);} |
				"ngeqq;" @{append_codepoint(8807);append_codepoint(824);} |
				"ngeqslant;" @{append_codepoint(10878);append_codepoint(824);} |
				"nges;" @{append_codepoint(10878);append_codepoint(824);} |
				"nGg;" @{append_codepoint(8921);append_codepoint(824);} |
				"ngsim;" @{append_codepoint(8821);} |
				"nGt;" @{append_codepoint(8811);append_codepoint(8402);} |
				"ngt;" @{append_codepoint(8815);} |
				"ngtr;" @{append_codepoint(8815);} |
				"nGtv;" @{append_codepoint(8811);append_codepoint(824);} |
				"nhArr;" @{append_codepoint(8654);} |
				"nharr;" @{append_codepoint(8622);} |
				"nhpar;" @{append_codepoint(10994);} |
				"ni;" @{append_codepoint(8715);} |
				"nis;" @{append_codepoint(8956);} |
				"nisd;" @{append_codepoint(8954);} |
				"niv;" @{append_codepoint(8715);} |
				"NJcy;" @{append_codepoint(1034);} |
				"njcy;" @{append_codepoint(1114);} |
				"nlArr;" @{append_codepoint(8653);} |
				"nlarr;" @{append_codepoint(8602);} |
				"nldr;" @{append_codepoint(8229);} |
				"nlE;" @{append_codepoint(8806);append_codepoint(824);} |
				"nle;" @{append_codepoint(8816);} |
				"nLeftarrow;" @{append_codepoint(8653);} |
				"nleftarrow;" @{append_codepoint(8602);} |
				"nLeftrightarrow;" @{append_codepoint(8654);} |
				"nleftrightarrow;" @{append_codepoint(8622);} |
				"nleq;" @{append_codepoint(8816);} |
				"nleqq;" @{append_codepoint(8806);append_codepoint(824);} |
				"nleqslant;" @{append_codepoint(10877);append_codepoint(824);} |
				"nles;" @{append_codepoint(10877);append_codepoint(824);} |
				"nless;" @{append_codepoint(8814);} |
				"nLl;" @{append_codepoint(8920);append_codepoint(824);} |
				"nlsim;" @{append_codepoint(8820);} |
				"nLt;" @{append_codepoint(8810);append_codepoint(8402);} |
				"nlt;" @{append_codepoint(8814);} |
				"nltri;" @{append_codepoint(8938);} |
				"nltrie;" @{append_codepoint(8940);} |
				"nLtv;" @{append_codepoint(8810);append_codepoint(824);} |
				"nmid;" @{append_codepoint(8740);} |
				"NoBreak;" @{append_codepoint(8288);} |
				"NonBreakingSpace;" @{append_codepoint(160);} |
				"Nopf;" @{append_codepoint(8469);} |
				"nopf;" @{append_codepoint(120159);} |
				"Not;" @{append_codepoint(10988);} |
				"not;" @{append_codepoint(172);} |
				"NotCongruent;" @{append_codepoint(8802);} |
				"NotCupCap;" @{append_codepoint(8813);} |
				"NotDoubleVerticalBar;" @{append_codepoint(8742);} |
				"NotElement;" @{append_codepoint(8713);} |
				"NotEqual;" @{append_codepoint(8800);} |
				"NotEqualTilde;" @{append_codepoint(8770);append_codepoint(824);} |
				"NotExists;" @{append_codepoint(8708);} |
				"NotGreater;" @{append_codepoint(8815);} |
				"NotGreaterEqual;" @{append_codepoint(8817);} |
				"NotGreaterFullEqual;" @{append_codepoint(8807);append_codepoint(824);} |
				"NotGreaterGreater;" @{append_codepoint(8811);append_codepoint(824);} |
				"NotGreaterLess;" @{append_codepoint(8825);} |
				"NotGreaterSlantEqual;" @{append_codepoint(10878);append_codepoint(824);} |
				"NotGreaterTilde;" @{append_codepoint(8821);} |
				"NotHumpDownHump;" @{append_codepoint(8782);append_codepoint(824);} |
				"NotHumpEqual;" @{append_codepoint(8783);append_codepoint(824);} |
				"notin;" @{append_codepoint(8713);} |
				"notindot;" @{append_codepoint(8949);append_codepoint(824);} |
				"notinE;" @{append_codepoint(8953);append_codepoint(824);} |
				"notinva;" @{append_codepoint(8713);} |
				"notinvb;" @{append_codepoint(8951);} |
				"notinvc;" @{append_codepoint(8950);} |
				"NotLeftTriangle;" @{append_codepoint(8938);} |
				"NotLeftTriangleBar;" @{append_codepoint(10703);append_codepoint(824);} |
				"NotLeftTriangleEqual;" @{append_codepoint(8940);} |
				"NotLess;" @{append_codepoint(8814);} |
				"NotLessEqual;" @{append_codepoint(8816);} |
				"NotLessGreater;" @{append_codepoint(8824);} |
				"NotLessLess;" @{append_codepoint(8810);append_codepoint(824);} |
				"NotLessSlantEqual;" @{append_codepoint(10877);append_codepoint(824);} |
				"NotLessTilde;" @{append_codepoint(8820);} |
				"NotNestedGreaterGreater;" @{append_codepoint(10914);append_codepoint(824);} |
				"NotNestedLessLess;" @{append_codepoint(10913);append_codepoint(824);} |
				"notni;" @{append_codepoint(8716);} |
				"notniva;" @{append_codepoint(8716);} |
				"notnivb;" @{append_codepoint(8958);} |
				"notnivc;" @{append_codepoint(8957);} |
				"NotPrecedes;" @{append_codepoint(8832);} |
				"NotPrecedesEqual;" @{append_codepoint(10927);append_codepoint(824);} |
				"NotPrecedesSlantEqual;" @{append_codepoint(8928);} |
				"NotReverseElement;" @{append_codepoint(8716);} |
				"NotRightTriangle;" @{append_codepoint(8939);} |
				"NotRightTriangleBar;" @{append_codepoint(10704);append_codepoint(824);} |
				"NotRightTriangleEqual;" @{append_codepoint(8941);} |
				"NotSquareSubset;" @{append_codepoint(8847);append_codepoint(824);} |
				"NotSquareSubsetEqual;" @{append_codepoint(8930);} |
				"NotSquareSuperset;" @{append_codepoint(8848);append_codepoint(824);} |
				"NotSquareSupersetEqual;" @{append_codepoint(8931);} |
				"NotSubset;" @{append_codepoint(8834);append_codepoint(8402);} |
				"NotSubsetEqual;" @{append_codepoint(8840);} |
				"NotSucceeds;" @{append_codepoint(8833);} |
				"NotSucceedsEqual;" @{append_codepoint(10928);append_codepoint(824);} |
				"NotSucceedsSlantEqual;" @{append_codepoint(8929);} |
				"NotSucceedsTilde;" @{append_codepoint(8831);append_codepoint(824);} |
				"NotSuperset;" @{append_codepoint(8835);append_codepoint(8402);} |
				"NotSupersetEqual;" @{append_codepoint(8841);} |
				"NotTilde;" @{append_codepoint(8769);} |
				"NotTildeEqual;" @{append_codepoint(8772);} |
				"NotTildeFullEqual;" @{append_codepoint(8775);} |
				"NotTildeTilde;" @{append_codepoint(8777);} |
				"NotVerticalBar;" @{append_codepoint(8740);} |
				"npar;" @{append_codepoint(8742);} |
				"nparallel;" @{append_codepoint(8742);} |
				"nparsl;" @{append_codepoint(11005);append_codepoint(8421);} |
				"npart;" @{append_codepoint(8706);append_codepoint(824);} |
				"npolint;" @{append_codepoint(10772);} |
				"npr;" @{append_codepoint(8832);} |
				"nprcue;" @{append_codepoint(8928);} |
				"npre;" @{append_codepoint(10927);append_codepoint(824);} |
				"nprec;" @{append_codepoint(8832);} |
				"npreceq;" @{append_codepoint(10927);append_codepoint(824);} |
				"nrArr;" @{append_codepoint(8655);} |
				"nrarr;" @{append_codepoint(8603);} |
				"nrarrc;" @{append_codepoint(10547);append_codepoint(824);} |
				"nrarrw;" @{append_codepoint(8605);append_codepoint(824);} |
				"nRightarrow;" @{append_codepoint(8655);} |
				"nrightarrow;" @{append_codepoint(8603);} |
				"nrtri;" @{append_codepoint(8939);} |
				"nrtrie;" @{append_codepoint(8941);} |
				"nsc;" @{append_codepoint(8833);} |
				"nsccue;" @{append_codepoint(8929);} |
				"nsce;" @{append_codepoint(10928);append_codepoint(824);} |
				"Nscr;" @{append_codepoint(119977);} |
				"nscr;" @{append_codepoint(120003);} |
				"nshortmid;" @{append_codepoint(8740);} |
				"nshortparallel;" @{append_codepoint(8742);} |
				"nsim;" @{append_codepoint(8769);} |
				"nsime;" @{append_codepoint(8772);} |
				"nsimeq;" @{append_codepoint(8772);} |
				"nsmid;" @{append_codepoint(8740);} |
				"nspar;" @{append_codepoint(8742);} |
				"nsqsube;" @{append_codepoint(8930);} |
				"nsqsupe;" @{append_codepoint(8931);} |
				"nsub;" @{append_codepoint(8836);} |
				"nsubE;" @{append_codepoint(10949);append_codepoint(824);} |
				"nsube;" @{append_codepoint(8840);} |
				"nsubset;" @{append_codepoint(8834);append_codepoint(8402);} |
				"nsubseteq;" @{append_codepoint(8840);} |
				"nsubseteqq;" @{append_codepoint(10949);append_codepoint(824);} |
				"nsucc;" @{append_codepoint(8833);} |
				"nsucceq;" @{append_codepoint(10928);append_codepoint(824);} |
				"nsup;" @{append_codepoint(8837);} |
				"nsupE;" @{append_codepoint(10950);append_codepoint(824);} |
				"nsupe;" @{append_codepoint(8841);} |
				"nsupset;" @{append_codepoint(8835);append_codepoint(8402);} |
				"nsupseteq;" @{append_codepoint(8841);} |
				"nsupseteqq;" @{append_codepoint(10950);append_codepoint(824);} |
				"ntgl;" @{append_codepoint(8825);} |
				"Ntilde;" @{append_codepoint(209);} |
				"ntilde;" @{append_codepoint(241);} |
				"ntlg;" @{append_codepoint(8824);} |
				"ntriangleleft;" @{append_codepoint(8938);} |
				"ntrianglelefteq;" @{append_codepoint(8940);} |
				"ntriangleright;" @{append_codepoint(8939);} |
				"ntrianglerighteq;" @{append_codepoint(8941);} |
				"Nu;" @{append_codepoint(925);} |
				"nu;" @{append_codepoint(957);} |
				"num;" @{append_codepoint(35);} |
				"numero;" @{append_codepoint(8470);} |
				"numsp;" @{append_codepoint(8199);} |
				"nvap;" @{append_codepoint(8781);append_codepoint(8402);} |
				"nVDash;" @{append_codepoint(8879);} |
				"nVdash;" @{append_codepoint(8878);} |
				"nvDash;" @{append_codepoint(8877);} |
				"nvdash;" @{append_codepoint(8876);} |
				"nvge;" @{append_codepoint(8805);append_codepoint(8402);} |
				"nvgt;" @{append_codepoint(62);append_codepoint(8402);} |
				"nvHarr;" @{append_codepoint(10500);} |
				"nvinfin;" @{append_codepoint(10718);} |
				"nvlArr;" @{append_codepoint(10498);} |
				"nvle;" @{append_codepoint(8804);append_codepoint(8402);} |
				"nvlt;" @{append_codepoint(60);append_codepoint(8402);} |
				"nvltrie;" @{append_codepoint(8884);append_codepoint(8402);} |
				"nvrArr;" @{append_codepoint(10499);} |
				"nvrtrie;" @{append_codepoint(8885);append_codepoint(8402);} |
				"nvsim;" @{append_codepoint(8764);append_codepoint(8402);} |
				"nwarhk;" @{append_codepoint(10531);} |
				"nwArr;" @{append_codepoint(8662);} |
				"nwarr;" @{append_codepoint(8598);} |
				"nwarrow;" @{append_codepoint(8598);} |
				"nwnear;" @{append_codepoint(10535);} |
				"Oacute;" @{append_codepoint(211);} |
				"oacute;" @{append_codepoint(243);} |
				"oast;" @{append_codepoint(8859);} |
				"ocir;" @{append_codepoint(8858);} |
				"Ocirc;" @{append_codepoint(212);} |
				"ocirc;" @{append_codepoint(244);} |
				"Ocy;" @{append_codepoint(1054);} |
				"ocy;" @{append_codepoint(1086);} |
				"odash;" @{append_codepoint(8861);} |
				"Odblac;" @{append_codepoint(336);} |
				"odblac;" @{append_codepoint(337);} |
				"odiv;" @{append_codepoint(10808);} |
				"odot;" @{append_codepoint(8857);} |
				"odsold;" @{append_codepoint(10684);} |
				"OElig;" @{append_codepoint(338);} |
				"oelig;" @{append_codepoint(339);} |
				"ofcir;" @{append_codepoint(10687);} |
				"Ofr;" @{append_codepoint(120082);} |
				"ofr;" @{append_codepoint(120108);} |
				"ogon;" @{append_codepoint(731);} |
				"Ograve;" @{append_codepoint(210);} |
				"ograve;" @{append_codepoint(242);} |
				"ogt;" @{append_codepoint(10689);} |
				"ohbar;" @{append_codepoint(10677);} |
				"ohm;" @{append_codepoint(937);} |
				"oint;" @{append_codepoint(8750);} |
				"olarr;" @{append_codepoint(8634);} |
				"olcir;" @{append_codepoint(10686);} |
				"olcross;" @{append_codepoint(10683);} |
				"oline;" @{append_codepoint(8254);} |
				"olt;" @{append_codepoint(10688);} |
				"Omacr;" @{append_codepoint(332);} |
				"omacr;" @{append_codepoint(333);} |
				"Omega;" @{append_codepoint(937);} |
				"omega;" @{append_codepoint(969);} |
				"Omicron;" @{append_codepoint(927);} |
				"omicron;" @{append_codepoint(959);} |
				"omid;" @{append_codepoint(10678);} |
				"ominus;" @{append_codepoint(8854);} |
				"Oopf;" @{append_codepoint(120134);} |
				"oopf;" @{append_codepoint(120160);} |
				"opar;" @{append_codepoint(10679);} |
				"OpenCurlyDoubleQuote;" @{append_codepoint(8220);} |
				"OpenCurlyQuote;" @{append_codepoint(8216);} |
				"operp;" @{append_codepoint(10681);} |
				"oplus;" @{append_codepoint(8853);} |
				"Or;" @{append_codepoint(10836);} |
				"or;" @{append_codepoint(8744);} |
				"orarr;" @{append_codepoint(8635);} |
				"ord;" @{append_codepoint(10845);} |
				"order;" @{append_codepoint(8500);} |
				"orderof;" @{append_codepoint(8500);} |
				"ordf;" @{append_codepoint(170);} |
				"ordm;" @{append_codepoint(186);} |
				"origof;" @{append_codepoint(8886);} |
				"oror;" @{append_codepoint(10838);} |
				"orslope;" @{append_codepoint(10839);} |
				"orv;" @{append_codepoint(10843);} |
				"oS;" @{append_codepoint(9416);} |
				"Oscr;" @{append_codepoint(119978);} |
				"oscr;" @{append_codepoint(8500);} |
				"Oslash;" @{append_codepoint(216);} |
				"oslash;" @{append_codepoint(248);} |
				"osol;" @{append_codepoint(8856);} |
				"Otilde;" @{append_codepoint(213);} |
				"otilde;" @{append_codepoint(245);} |
				"Otimes;" @{append_codepoint(10807);} |
				"otimes;" @{append_codepoint(8855);} |
				"otimesas;" @{append_codepoint(10806);} |
				"Ouml;" @{append_codepoint(214);} |
				"ouml;" @{append_codepoint(246);} |
				"ovbar;" @{append_codepoint(9021);} |
				"OverBar;" @{append_codepoint(8254);} |
				"OverBrace;" @{append_codepoint(9182);} |
				"OverBracket;" @{append_codepoint(9140);} |
				"OverParenthesis;" @{append_codepoint(9180);} |
				"par;" @{append_codepoint(8741);} |
				"para;" @{append_codepoint(182);} |
				"parallel;" @{append_codepoint(8741);} |
				"parsim;" @{append_codepoint(10995);} |
				"parsl;" @{append_codepoint(11005);} |
				"part;" @{append_codepoint(8706);} |
				"PartialD;" @{append_codepoint(8706);} |
				"Pcy;" @{append_codepoint(1055);} |
				"pcy;" @{append_codepoint(1087);} |
				"percnt;" @{append_codepoint(37);} |
				"period;" @{append_codepoint(46);} |
				"permil;" @{append_codepoint(8240);} |
				"perp;" @{append_codepoint(8869);} |
				"pertenk;" @{append_codepoint(8241);} |
				"Pfr;" @{append_codepoint(120083);} |
				"pfr;" @{append_codepoint(120109);} |
				"Phi;" @{append_codepoint(934);} |
				"phi;" @{append_codepoint(966);} |
				"phiv;" @{append_codepoint(981);} |
				"phmmat;" @{append_codepoint(8499);} |
				"phone;" @{append_codepoint(9742);} |
				"Pi;" @{append_codepoint(928);} |
				"pi;" @{append_codepoint(960);} |
				"pitchfork;" @{append_codepoint(8916);} |
				"piv;" @{append_codepoint(982);} |
				"planck;" @{append_codepoint(8463);} |
				"planckh;" @{append_codepoint(8462);} |
				"plankv;" @{append_codepoint(8463);} |
				"plus;" @{append_codepoint(43);} |
				"plusacir;" @{append_codepoint(10787);} |
				"plusb;" @{append_codepoint(8862);} |
				"pluscir;" @{append_codepoint(10786);} |
				"plusdo;" @{append_codepoint(8724);} |
				"plusdu;" @{append_codepoint(10789);} |
				"pluse;" @{append_codepoint(10866);} |
				"PlusMinus;" @{append_codepoint(177);} |
				"plusmn;" @{append_codepoint(177);} |
				"plussim;" @{append_codepoint(10790);} |
				"plustwo;" @{append_codepoint(10791);} |
				"pm;" @{append_codepoint(177);} |
				"Poincareplane;" @{append_codepoint(8460);} |
				"pointint;" @{append_codepoint(10773);} |
				"Popf;" @{append_codepoint(8473);} |
				"popf;" @{append_codepoint(120161);} |
				"pound;" @{append_codepoint(163);} |
				"Pr;" @{append_codepoint(10939);} |
				"pr;" @{append_codepoint(8826);} |
				"prap;" @{append_codepoint(10935);} |
				"prcue;" @{append_codepoint(8828);} |
				"prE;" @{append_codepoint(10931);} |
				"pre;" @{append_codepoint(10927);} |
				"prec;" @{append_codepoint(8826);} |
				"precapprox;" @{append_codepoint(10935);} |
				"preccurlyeq;" @{append_codepoint(8828);} |
				"Precedes;" @{append_codepoint(8826);} |
				"PrecedesEqual;" @{append_codepoint(10927);} |
				"PrecedesSlantEqual;" @{append_codepoint(8828);} |
				"PrecedesTilde;" @{append_codepoint(8830);} |
				"preceq;" @{append_codepoint(10927);} |
				"precnapprox;" @{append_codepoint(10937);} |
				"precneqq;" @{append_codepoint(10933);} |
				"precnsim;" @{append_codepoint(8936);} |
				"precsim;" @{append_codepoint(8830);} |
				"Prime;" @{append_codepoint(8243);} |
				"prime;" @{append_codepoint(8242);} |
				"primes;" @{append_codepoint(8473);} |
				"prnap;" @{append_codepoint(10937);} |
				"prnE;" @{append_codepoint(10933);} |
				"prnsim;" @{append_codepoint(8936);} |
				"prod;" @{append_codepoint(8719);} |
				"Product;" @{append_codepoint(8719);} |
				"profalar;" @{append_codepoint(9006);} |
				"profline;" @{append_codepoint(8978);} |
				"profsurf;" @{append_codepoint(8979);} |
				"prop;" @{append_codepoint(8733);} |
				"Proportion;" @{append_codepoint(8759);} |
				"Proportional;" @{append_codepoint(8733);} |
				"propto;" @{append_codepoint(8733);} |
				"prsim;" @{append_codepoint(8830);} |
				"prurel;" @{append_codepoint(8880);} |
				"Pscr;" @{append_codepoint(119979);} |
				"pscr;" @{append_codepoint(120005);} |
				"Psi;" @{append_codepoint(936);} |
				"psi;" @{append_codepoint(968);} |
				"puncsp;" @{append_codepoint(8200);} |
				"Qfr;" @{append_codepoint(120084);} |
				"qfr;" @{append_codepoint(120110);} |
				"qint;" @{append_codepoint(10764);} |
				"Qopf;" @{append_codepoint(8474);} |
				"qopf;" @{append_codepoint(120162);} |
				"qprime;" @{append_codepoint(8279);} |
				"Qscr;" @{append_codepoint(119980);} |
				"qscr;" @{append_codepoint(120006);} |
				"quaternions;" @{append_codepoint(8461);} |
				"quatint;" @{append_codepoint(10774);} |
				"quest;" @{append_codepoint(63);} |
				"questeq;" @{append_codepoint(8799);} |
				"QUOT;" @{append_codepoint(34);} |
				"quot;" @{append_codepoint(34);} |
				"rAarr;" @{append_codepoint(8667);} |
				"race;" @{append_codepoint(8765);append_codepoint(817);} |
				"Racute;" @{append_codepoint(340);} |
				"racute;" @{append_codepoint(341);} |
				"radic;" @{append_codepoint(8730);} |
				"raemptyv;" @{append_codepoint(10675);} |
				"Rang;" @{append_codepoint(10219);} |
				"rang;" @{append_codepoint(10217);} |
				"rangd;" @{append_codepoint(10642);} |
				"range;" @{append_codepoint(10661);} |
				"rangle;" @{append_codepoint(10217);} |
				"raquo;" @{append_codepoint(187);} |
				"Rarr;" @{append_codepoint(8608);} |
				"rArr;" @{append_codepoint(8658);} |
				"rarr;" @{append_codepoint(8594);} |
				"rarrap;" @{append_codepoint(10613);} |
				"rarrb;" @{append_codepoint(8677);} |
				"rarrbfs;" @{append_codepoint(10528);} |
				"rarrc;" @{append_codepoint(10547);} |
				"rarrfs;" @{append_codepoint(10526);} |
				"rarrhk;" @{append_codepoint(8618);} |
				"rarrlp;" @{append_codepoint(8620);} |
				"rarrpl;" @{append_codepoint(10565);} |
				"rarrsim;" @{append_codepoint(10612);} |
				"Rarrtl;" @{append_codepoint(10518);} |
				"rarrtl;" @{append_codepoint(8611);} |
				"rarrw;" @{append_codepoint(8605);} |
				"rAtail;" @{append_codepoint(10524);} |
				"ratail;" @{append_codepoint(10522);} |
				"ratio;" @{append_codepoint(8758);} |
				"rationals;" @{append_codepoint(8474);} |
				"RBarr;" @{append_codepoint(10512);} |
				"rBarr;" @{append_codepoint(10511);} |
				"rbarr;" @{append_codepoint(10509);} |
				"rbbrk;" @{append_codepoint(10099);} |
				"rbrace;" @{append_codepoint(125);} |
				"rbrack;" @{append_codepoint(93);} |
				"rbrke;" @{append_codepoint(10636);} |
				"rbrksld;" @{append_codepoint(10638);} |
				"rbrkslu;" @{append_codepoint(10640);} |
				"Rcaron;" @{append_codepoint(344);} |
				"rcaron;" @{append_codepoint(345);} |
				"Rcedil;" @{append_codepoint(342);} |
				"rcedil;" @{append_codepoint(343);} |
				"rceil;" @{append_codepoint(8969);} |
				"rcub;" @{append_codepoint(125);} |
				"Rcy;" @{append_codepoint(1056);} |
				"rcy;" @{append_codepoint(1088);} |
				"rdca;" @{append_codepoint(10551);} |
				"rdldhar;" @{append_codepoint(10601);} |
				"rdquo;" @{append_codepoint(8221);} |
				"rdquor;" @{append_codepoint(8221);} |
				"rdsh;" @{append_codepoint(8627);} |
				"Re;" @{append_codepoint(8476);} |
				"real;" @{append_codepoint(8476);} |
				"realine;" @{append_codepoint(8475);} |
				"realpart;" @{append_codepoint(8476);} |
				"reals;" @{append_codepoint(8477);} |
				"rect;" @{append_codepoint(9645);} |
				"REG;" @{append_codepoint(174);} |
				"reg;" @{append_codepoint(174);} |
				"ReverseElement;" @{append_codepoint(8715);} |
				"ReverseEquilibrium;" @{append_codepoint(8651);} |
				"ReverseUpEquilibrium;" @{append_codepoint(10607);} |
				"rfisht;" @{append_codepoint(10621);} |
				"rfloor;" @{append_codepoint(8971);} |
				"Rfr;" @{append_codepoint(8476);} |
				"rfr;" @{append_codepoint(120111);} |
				"rHar;" @{append_codepoint(10596);} |
				"rhard;" @{append_codepoint(8641);} |
				"rharu;" @{append_codepoint(8640);} |
				"rharul;" @{append_codepoint(10604);} |
				"Rho;" @{append_codepoint(929);} |
				"rho;" @{append_codepoint(961);} |
				"rhov;" @{append_codepoint(1009);} |
				"RightAngleBracket;" @{append_codepoint(10217);} |
				"RightArrow;" @{append_codepoint(8594);} |
				"Rightarrow;" @{append_codepoint(8658);} |
				"rightarrow;" @{append_codepoint(8594);} |
				"RightArrowBar;" @{append_codepoint(8677);} |
				"RightArrowLeftArrow;" @{append_codepoint(8644);} |
				"rightarrowtail;" @{append_codepoint(8611);} |
				"RightCeiling;" @{append_codepoint(8969);} |
				"RightDoubleBracket;" @{append_codepoint(10215);} |
				"RightDownTeeVector;" @{append_codepoint(10589);} |
				"RightDownVector;" @{append_codepoint(8642);} |
				"RightDownVectorBar;" @{append_codepoint(10581);} |
				"RightFloor;" @{append_codepoint(8971);} |
				"rightharpoondown;" @{append_codepoint(8641);} |
				"rightharpoonup;" @{append_codepoint(8640);} |
				"rightleftarrows;" @{append_codepoint(8644);} |
				"rightleftharpoons;" @{append_codepoint(8652);} |
				"rightrightarrows;" @{append_codepoint(8649);} |
				"rightsquigarrow;" @{append_codepoint(8605);} |
				"RightTee;" @{append_codepoint(8866);} |
				"RightTeeArrow;" @{append_codepoint(8614);} |
				"RightTeeVector;" @{append_codepoint(10587);} |
				"rightthreetimes;" @{append_codepoint(8908);} |
				"RightTriangle;" @{append_codepoint(8883);} |
				"RightTriangleBar;" @{append_codepoint(10704);} |
				"RightTriangleEqual;" @{append_codepoint(8885);} |
				"RightUpDownVector;" @{append_codepoint(10575);} |
				"RightUpTeeVector;" @{append_codepoint(10588);} |
				"RightUpVector;" @{append_codepoint(8638);} |
				"RightUpVectorBar;" @{append_codepoint(10580);} |
				"RightVector;" @{append_codepoint(8640);} |
				"RightVectorBar;" @{append_codepoint(10579);} |
				"ring;" @{append_codepoint(730);} |
				"risingdotseq;" @{append_codepoint(8787);} |
				"rlarr;" @{append_codepoint(8644);} |
				"rlhar;" @{append_codepoint(8652);} |
				"rlm;" @{append_codepoint(8207);} |
				"rmoust;" @{append_codepoint(9137);} |
				"rmoustache;" @{append_codepoint(9137);} |
				"rnmid;" @{append_codepoint(10990);} |
				"roang;" @{append_codepoint(10221);} |
				"roarr;" @{append_codepoint(8702);} |
				"robrk;" @{append_codepoint(10215);} |
				"ropar;" @{append_codepoint(10630);} |
				"Ropf;" @{append_codepoint(8477);} |
				"ropf;" @{append_codepoint(120163);} |
				"roplus;" @{append_codepoint(10798);} |
				"rotimes;" @{append_codepoint(10805);} |
				"RoundImplies;" @{append_codepoint(10608);} |
				"rpar;" @{append_codepoint(41);} |
				"rpargt;" @{append_codepoint(10644);} |
				"rppolint;" @{append_codepoint(10770);} |
				"rrarr;" @{append_codepoint(8649);} |
				"Rrightarrow;" @{append_codepoint(8667);} |
				"rsaquo;" @{append_codepoint(8250);} |
				"Rscr;" @{append_codepoint(8475);} |
				"rscr;" @{append_codepoint(120007);} |
				"Rsh;" @{append_codepoint(8625);} |
				"rsh;" @{append_codepoint(8625);} |
				"rsqb;" @{append_codepoint(93);} |
				"rsquo;" @{append_codepoint(8217);} |
				"rsquor;" @{append_codepoint(8217);} |
				"rthree;" @{append_codepoint(8908);} |
				"rtimes;" @{append_codepoint(8906);} |
				"rtri;" @{append_codepoint(9657);} |
				"rtrie;" @{append_codepoint(8885);} |
				"rtrif;" @{append_codepoint(9656);} |
				"rtriltri;" @{append_codepoint(10702);} |
				"RuleDelayed;" @{append_codepoint(10740);} |
				"ruluhar;" @{append_codepoint(10600);} |
				"rx;" @{append_codepoint(8478);} |
				"Sacute;" @{append_codepoint(346);} |
				"sacute;" @{append_codepoint(347);} |
				"sbquo;" @{append_codepoint(8218);} |
				"Sc;" @{append_codepoint(10940);} |
				"sc;" @{append_codepoint(8827);} |
				"scap;" @{append_codepoint(10936);} |
				"Scaron;" @{append_codepoint(352);} |
				"scaron;" @{append_codepoint(353);} |
				"sccue;" @{append_codepoint(8829);} |
				"scE;" @{append_codepoint(10932);} |
				"sce;" @{append_codepoint(10928);} |
				"Scedil;" @{append_codepoint(350);} |
				"scedil;" @{append_codepoint(351);} |
				"Scirc;" @{append_codepoint(348);} |
				"scirc;" @{append_codepoint(349);} |
				"scnap;" @{append_codepoint(10938);} |
				"scnE;" @{append_codepoint(10934);} |
				"scnsim;" @{append_codepoint(8937);} |
				"scpolint;" @{append_codepoint(10771);} |
				"scsim;" @{append_codepoint(8831);} |
				"Scy;" @{append_codepoint(1057);} |
				"scy;" @{append_codepoint(1089);} |
				"sdot;" @{append_codepoint(8901);} |
				"sdotb;" @{append_codepoint(8865);} |
				"sdote;" @{append_codepoint(10854);} |
				"searhk;" @{append_codepoint(10533);} |
				"seArr;" @{append_codepoint(8664);} |
				"searr;" @{append_codepoint(8600);} |
				"searrow;" @{append_codepoint(8600);} |
				"sect;" @{append_codepoint(167);} |
				"semi;" @{append_codepoint(59);} |
				"seswar;" @{append_codepoint(10537);} |
				"setminus;" @{append_codepoint(8726);} |
				"setmn;" @{append_codepoint(8726);} |
				"sext;" @{append_codepoint(10038);} |
				"Sfr;" @{append_codepoint(120086);} |
				"sfr;" @{append_codepoint(120112);} |
				"sfrown;" @{append_codepoint(8994);} |
				"sharp;" @{append_codepoint(9839);} |
				"SHCHcy;" @{append_codepoint(1065);} |
				"shchcy;" @{append_codepoint(1097);} |
				"SHcy;" @{append_codepoint(1064);} |
				"shcy;" @{append_codepoint(1096);} |
				"ShortDownArrow;" @{append_codepoint(8595);} |
				"ShortLeftArrow;" @{append_codepoint(8592);} |
				"shortmid;" @{append_codepoint(8739);} |
				"shortparallel;" @{append_codepoint(8741);} |
				"ShortRightArrow;" @{append_codepoint(8594);} |
				"ShortUpArrow;" @{append_codepoint(8593);} |
				"shy;" @{append_codepoint(173);} |
				"Sigma;" @{append_codepoint(931);} |
				"sigma;" @{append_codepoint(963);} |
				"sigmaf;" @{append_codepoint(962);} |
				"sigmav;" @{append_codepoint(962);} |
				"sim;" @{append_codepoint(8764);} |
				"simdot;" @{append_codepoint(10858);} |
				"sime;" @{append_codepoint(8771);} |
				"simeq;" @{append_codepoint(8771);} |
				"simg;" @{append_codepoint(10910);} |
				"simgE;" @{append_codepoint(10912);} |
				"siml;" @{append_codepoint(10909);} |
				"simlE;" @{append_codepoint(10911);} |
				"simne;" @{append_codepoint(8774);} |
				"simplus;" @{append_codepoint(10788);} |
				"simrarr;" @{append_codepoint(10610);} |
				"slarr;" @{append_codepoint(8592);} |
				"SmallCircle;" @{append_codepoint(8728);} |
				"smallsetminus;" @{append_codepoint(8726);} |
				"smashp;" @{append_codepoint(10803);} |
				"smeparsl;" @{append_codepoint(10724);} |
				"smid;" @{append_codepoint(8739);} |
				"smile;" @{append_codepoint(8995);} |
				"smt;" @{append_codepoint(10922);} |
				"smte;" @{append_codepoint(10924);} |
				"smtes;" @{append_codepoint(10924);append_codepoint(65024);} |
				"SOFTcy;" @{append_codepoint(1068);} |
				"softcy;" @{append_codepoint(1100);} |
				"sol;" @{append_codepoint(47);} |
				"solb;" @{append_codepoint(10692);} |
				"solbar;" @{append_codepoint(9023);} |
				"Sopf;" @{append_codepoint(120138);} |
				"sopf;" @{append_codepoint(120164);} |
				"spades;" @{append_codepoint(9824);} |
				"spadesuit;" @{append_codepoint(9824);} |
				"spar;" @{append_codepoint(8741);} |
				"sqcap;" @{append_codepoint(8851);} |
				"sqcaps;" @{append_codepoint(8851);append_codepoint(65024);} |
				"sqcup;" @{append_codepoint(8852);} |
				"sqcups;" @{append_codepoint(8852);append_codepoint(65024);} |
				"Sqrt;" @{append_codepoint(8730);} |
				"sqsub;" @{append_codepoint(8847);} |
				"sqsube;" @{append_codepoint(8849);} |
				"sqsubset;" @{append_codepoint(8847);} |
				"sqsubseteq;" @{append_codepoint(8849);} |
				"sqsup;" @{append_codepoint(8848);} |
				"sqsupe;" @{append_codepoint(8850);} |
				"sqsupset;" @{append_codepoint(8848);} |
				"sqsupseteq;" @{append_codepoint(8850);} |
				"squ;" @{append_codepoint(9633);} |
				"Square;" @{append_codepoint(9633);} |
				"square;" @{append_codepoint(9633);} |
				"SquareIntersection;" @{append_codepoint(8851);} |
				"SquareSubset;" @{append_codepoint(8847);} |
				"SquareSubsetEqual;" @{append_codepoint(8849);} |
				"SquareSuperset;" @{append_codepoint(8848);} |
				"SquareSupersetEqual;" @{append_codepoint(8850);} |
				"SquareUnion;" @{append_codepoint(8852);} |
				"squarf;" @{append_codepoint(9642);} |
				"squf;" @{append_codepoint(9642);} |
				"srarr;" @{append_codepoint(8594);} |
				"Sscr;" @{append_codepoint(119982);} |
				"sscr;" @{append_codepoint(120008);} |
				"ssetmn;" @{append_codepoint(8726);} |
				"ssmile;" @{append_codepoint(8995);} |
				"sstarf;" @{append_codepoint(8902);} |
				"Star;" @{append_codepoint(8902);} |
				"star;" @{append_codepoint(9734);} |
				"starf;" @{append_codepoint(9733);} |
				"straightepsilon;" @{append_codepoint(1013);} |
				"straightphi;" @{append_codepoint(981);} |
				"strns;" @{append_codepoint(175);} |
				"Sub;" @{append_codepoint(8912);} |
				"sub;" @{append_codepoint(8834);} |
				"subdot;" @{append_codepoint(10941);} |
				"subE;" @{append_codepoint(10949);} |
				"sube;" @{append_codepoint(8838);} |
				"subedot;" @{append_codepoint(10947);} |
				"submult;" @{append_codepoint(10945);} |
				"subnE;" @{append_codepoint(10955);} |
				"subne;" @{append_codepoint(8842);} |
				"subplus;" @{append_codepoint(10943);} |
				"subrarr;" @{append_codepoint(10617);} |
				"Subset;" @{append_codepoint(8912);} |
				"subset;" @{append_codepoint(8834);} |
				"subseteq;" @{append_codepoint(8838);} |
				"subseteqq;" @{append_codepoint(10949);} |
				"SubsetEqual;" @{append_codepoint(8838);} |
				"subsetneq;" @{append_codepoint(8842);} |
				"subsetneqq;" @{append_codepoint(10955);} |
				"subsim;" @{append_codepoint(10951);} |
				"subsub;" @{append_codepoint(10965);} |
				"subsup;" @{append_codepoint(10963);} |
				"succ;" @{append_codepoint(8827);} |
				"succapprox;" @{append_codepoint(10936);} |
				"succcurlyeq;" @{append_codepoint(8829);} |
				"Succeeds;" @{append_codepoint(8827);} |
				"SucceedsEqual;" @{append_codepoint(10928);} |
				"SucceedsSlantEqual;" @{append_codepoint(8829);} |
				"SucceedsTilde;" @{append_codepoint(8831);} |
				"succeq;" @{append_codepoint(10928);} |
				"succnapprox;" @{append_codepoint(10938);} |
				"succneqq;" @{append_codepoint(10934);} |
				"succnsim;" @{append_codepoint(8937);} |
				"succsim;" @{append_codepoint(8831);} |
				"SuchThat;" @{append_codepoint(8715);} |
				"Sum;" @{append_codepoint(8721);} |
				"sum;" @{append_codepoint(8721);} |
				"sung;" @{append_codepoint(9834);} |
				"Sup;" @{append_codepoint(8913);} |
				"sup;" @{append_codepoint(8835);} |
				"sup1;" @{append_codepoint(185);} |
				"sup2;" @{append_codepoint(178);} |
				"sup3;" @{append_codepoint(179);} |
				"supdot;" @{append_codepoint(10942);} |
				"supdsub;" @{append_codepoint(10968);} |
				"supE;" @{append_codepoint(10950);} |
				"supe;" @{append_codepoint(8839);} |
				"supedot;" @{append_codepoint(10948);} |
				"Superset;" @{append_codepoint(8835);} |
				"SupersetEqual;" @{append_codepoint(8839);} |
				"suphsol;" @{append_codepoint(10185);} |
				"suphsub;" @{append_codepoint(10967);} |
				"suplarr;" @{append_codepoint(10619);} |
				"supmult;" @{append_codepoint(10946);} |
				"supnE;" @{append_codepoint(10956);} |
				"supne;" @{append_codepoint(8843);} |
				"supplus;" @{append_codepoint(10944);} |
				"Supset;" @{append_codepoint(8913);} |
				"supset;" @{append_codepoint(8835);} |
				"supseteq;" @{append_codepoint(8839);} |
				"supseteqq;" @{append_codepoint(10950);} |
				"supsetneq;" @{append_codepoint(8843);} |
				"supsetneqq;" @{append_codepoint(10956);} |
				"supsim;" @{append_codepoint(10952);} |
				"supsub;" @{append_codepoint(10964);} |
				"supsup;" @{append_codepoint(10966);} |
				"swarhk;" @{append_codepoint(10534);} |
				"swArr;" @{append_codepoint(8665);} |
				"swarr;" @{append_codepoint(8601);} |
				"swarrow;" @{append_codepoint(8601);} |
				"swnwar;" @{append_codepoint(10538);} |
				"szlig;" @{append_codepoint(223);} |
				"Tab;" @{append_codepoint(9);} |
				"target;" @{append_codepoint(8982);} |
				"Tau;" @{append_codepoint(932);} |
				"tau;" @{append_codepoint(964);} |
				"tbrk;" @{append_codepoint(9140);} |
				"Tcaron;" @{append_codepoint(356);} |
				"tcaron;" @{append_codepoint(357);} |
				"Tcedil;" @{append_codepoint(354);} |
				"tcedil;" @{append_codepoint(355);} |
				"Tcy;" @{append_codepoint(1058);} |
				"tcy;" @{append_codepoint(1090);} |
				"tdot;" @{append_codepoint(8411);} |
				"telrec;" @{append_codepoint(8981);} |
				"Tfr;" @{append_codepoint(120087);} |
				"tfr;" @{append_codepoint(120113);} |
				"there4;" @{append_codepoint(8756);} |
				"Therefore;" @{append_codepoint(8756);} |
				"therefore;" @{append_codepoint(8756);} |
				"Theta;" @{append_codepoint(920);} |
				"theta;" @{append_codepoint(952);} |
				"thetasym;" @{append_codepoint(977);} |
				"thetav;" @{append_codepoint(977);} |
				"thickapprox;" @{append_codepoint(8776);} |
				"thicksim;" @{append_codepoint(8764);} |
				"ThickSpace;" @{append_codepoint(8287);append_codepoint(8202);} |
				"thinsp;" @{append_codepoint(8201);} |
				"ThinSpace;" @{append_codepoint(8201);} |
				"thkap;" @{append_codepoint(8776);} |
				"thksim;" @{append_codepoint(8764);} |
				"THORN;" @{append_codepoint(222);} |
				"thorn;" @{append_codepoint(254);} |
				"Tilde;" @{append_codepoint(8764);} |
				"tilde;" @{append_codepoint(732);} |
				"TildeEqual;" @{append_codepoint(8771);} |
				"TildeFullEqual;" @{append_codepoint(8773);} |
				"TildeTilde;" @{append_codepoint(8776);} |
				"times;" @{append_codepoint(215);} |
				"timesb;" @{append_codepoint(8864);} |
				"timesbar;" @{append_codepoint(10801);} |
				"timesd;" @{append_codepoint(10800);} |
				"tint;" @{append_codepoint(8749);} |
				"toea;" @{append_codepoint(10536);} |
				"top;" @{append_codepoint(8868);} |
				"topbot;" @{append_codepoint(9014);} |
				"topcir;" @{append_codepoint(10993);} |
				"Topf;" @{append_codepoint(120139);} |
				"topf;" @{append_codepoint(120165);} |
				"topfork;" @{append_codepoint(10970);} |
				"tosa;" @{append_codepoint(10537);} |
				"tprime;" @{append_codepoint(8244);} |
				"TRADE;" @{append_codepoint(8482);} |
				"trade;" @{append_codepoint(8482);} |
				"triangle;" @{append_codepoint(9653);} |
				"triangledown;" @{append_codepoint(9663);} |
				"triangleleft;" @{append_codepoint(9667);} |
				"trianglelefteq;" @{append_codepoint(8884);} |
				"triangleq;" @{append_codepoint(8796);} |
				"triangleright;" @{append_codepoint(9657);} |
				"trianglerighteq;" @{append_codepoint(8885);} |
				"tridot;" @{append_codepoint(9708);} |
				"trie;" @{append_codepoint(8796);} |
				"triminus;" @{append_codepoint(10810);} |
				"TripleDot;" @{append_codepoint(8411);} |
				"triplus;" @{append_codepoint(10809);} |
				"trisb;" @{append_codepoint(10701);} |
				"tritime;" @{append_codepoint(10811);} |
				"trpezium;" @{append_codepoint(9186);} |
				"Tscr;" @{append_codepoint(119983);} |
				"tscr;" @{append_codepoint(120009);} |
				"TScy;" @{append_codepoint(1062);} |
				"tscy;" @{append_codepoint(1094);} |
				"TSHcy;" @{append_codepoint(1035);} |
				"tshcy;" @{append_codepoint(1115);} |
				"Tstrok;" @{append_codepoint(358);} |
				"tstrok;" @{append_codepoint(359);} |
				"twixt;" @{append_codepoint(8812);} |
				"twoheadleftarrow;" @{append_codepoint(8606);} |
				"twoheadrightarrow;" @{append_codepoint(8608);} |
				"Uacute;" @{append_codepoint(218);} |
				"uacute;" @{append_codepoint(250);} |
				"Uarr;" @{append_codepoint(8607);} |
				"uArr;" @{append_codepoint(8657);} |
				"uarr;" @{append_codepoint(8593);} |
				"Uarrocir;" @{append_codepoint(10569);} |
				"Ubrcy;" @{append_codepoint(1038);} |
				"ubrcy;" @{append_codepoint(1118);} |
				"Ubreve;" @{append_codepoint(364);} |
				"ubreve;" @{append_codepoint(365);} |
				"Ucirc;" @{append_codepoint(219);} |
				"ucirc;" @{append_codepoint(251);} |
				"Ucy;" @{append_codepoint(1059);} |
				"ucy;" @{append_codepoint(1091);} |
				"udarr;" @{append_codepoint(8645);} |
				"Udblac;" @{append_codepoint(368);} |
				"udblac;" @{append_codepoint(369);} |
				"udhar;" @{append_codepoint(10606);} |
				"ufisht;" @{append_codepoint(10622);} |
				"Ufr;" @{append_codepoint(120088);} |
				"ufr;" @{append_codepoint(120114);} |
				"Ugrave;" @{append_codepoint(217);} |
				"ugrave;" @{append_codepoint(249);} |
				"uHar;" @{append_codepoint(10595);} |
				"uharl;" @{append_codepoint(8639);} |
				"uharr;" @{append_codepoint(8638);} |
				"uhblk;" @{append_codepoint(9600);} |
				"ulcorn;" @{append_codepoint(8988);} |
				"ulcorner;" @{append_codepoint(8988);} |
				"ulcrop;" @{append_codepoint(8975);} |
				"ultri;" @{append_codepoint(9720);} |
				"Umacr;" @{append_codepoint(362);} |
				"umacr;" @{append_codepoint(363);} |
				"uml;" @{append_codepoint(168);} |
				"UnderBar;" @{append_codepoint(95);} |
				"UnderBrace;" @{append_codepoint(9183);} |
				"UnderBracket;" @{append_codepoint(9141);} |
				"UnderParenthesis;" @{append_codepoint(9181);} |
				"Union;" @{append_codepoint(8899);} |
				"UnionPlus;" @{append_codepoint(8846);} |
				"Uogon;" @{append_codepoint(370);} |
				"uogon;" @{append_codepoint(371);} |
				"Uopf;" @{append_codepoint(120140);} |
				"uopf;" @{append_codepoint(120166);} |
				"UpArrow;" @{append_codepoint(8593);} |
				"Uparrow;" @{append_codepoint(8657);} |
				"uparrow;" @{append_codepoint(8593);} |
				"UpArrowBar;" @{append_codepoint(10514);} |
				"UpArrowDownArrow;" @{append_codepoint(8645);} |
				"UpDownArrow;" @{append_codepoint(8597);} |
				"Updownarrow;" @{append_codepoint(8661);} |
				"updownarrow;" @{append_codepoint(8597);} |
				"UpEquilibrium;" @{append_codepoint(10606);} |
				"upharpoonleft;" @{append_codepoint(8639);} |
				"upharpoonright;" @{append_codepoint(8638);} |
				"uplus;" @{append_codepoint(8846);} |
				"UpperLeftArrow;" @{append_codepoint(8598);} |
				"UpperRightArrow;" @{append_codepoint(8599);} |
				"Upsi;" @{append_codepoint(978);} |
				"upsi;" @{append_codepoint(965);} |
				"upsih;" @{append_codepoint(978);} |
				"Upsilon;" @{append_codepoint(933);} |
				"upsilon;" @{append_codepoint(965);} |
				"UpTee;" @{append_codepoint(8869);} |
				"UpTeeArrow;" @{append_codepoint(8613);} |
				"upuparrows;" @{append_codepoint(8648);} |
				"urcorn;" @{append_codepoint(8989);} |
				"urcorner;" @{append_codepoint(8989);} |
				"urcrop;" @{append_codepoint(8974);} |
				"Uring;" @{append_codepoint(366);} |
				"uring;" @{append_codepoint(367);} |
				"urtri;" @{append_codepoint(9721);} |
				"Uscr;" @{append_codepoint(119984);} |
				"uscr;" @{append_codepoint(120010);} |
				"utdot;" @{append_codepoint(8944);} |
				"Utilde;" @{append_codepoint(360);} |
				"utilde;" @{append_codepoint(361);} |
				"utri;" @{append_codepoint(9653);} |
				"utrif;" @{append_codepoint(9652);} |
				"uuarr;" @{append_codepoint(8648);} |
				"Uuml;" @{append_codepoint(220);} |
				"uuml;" @{append_codepoint(252);} |
				"uwangle;" @{append_codepoint(10663);} |
				"vangrt;" @{append_codepoint(10652);} |
				"varepsilon;" @{append_codepoint(1013);} |
				"varkappa;" @{append_codepoint(1008);} |
				"varnothing;" @{append_codepoint(8709);} |
				"varphi;" @{append_codepoint(981);} |
				"varpi;" @{append_codepoint(982);} |
				"varpropto;" @{append_codepoint(8733);} |
				"vArr;" @{append_codepoint(8661);} |
				"varr;" @{append_codepoint(8597);} |
				"varrho;" @{append_codepoint(1009);} |
				"varsigma;" @{append_codepoint(962);} |
				"varsubsetneq;" @{append_codepoint(8842);append_codepoint(65024);} |
				"varsubsetneqq;" @{append_codepoint(10955);append_codepoint(65024);} |
				"varsupsetneq;" @{append_codepoint(8843);append_codepoint(65024);} |
				"varsupsetneqq;" @{append_codepoint(10956);append_codepoint(65024);} |
				"vartheta;" @{append_codepoint(977);} |
				"vartriangleleft;" @{append_codepoint(8882);} |
				"vartriangleright;" @{append_codepoint(8883);} |
				"Vbar;" @{append_codepoint(10987);} |
				"vBar;" @{append_codepoint(10984);} |
				"vBarv;" @{append_codepoint(10985);} |
				"Vcy;" @{append_codepoint(1042);} |
				"vcy;" @{append_codepoint(1074);} |
				"VDash;" @{append_codepoint(8875);} |
				"Vdash;" @{append_codepoint(8873);} |
				"vDash;" @{append_codepoint(8872);} |
				"vdash;" @{append_codepoint(8866);} |
				"Vdashl;" @{append_codepoint(10982);} |
				"Vee;" @{append_codepoint(8897);} |
				"vee;" @{append_codepoint(8744);} |
				"veebar;" @{append_codepoint(8891);} |
				"veeeq;" @{append_codepoint(8794);} |
				"vellip;" @{append_codepoint(8942);} |
				"Verbar;" @{append_codepoint(8214);} |
				"verbar;" @{append_codepoint(124);} |
				"Vert;" @{append_codepoint(8214);} |
				"vert;" @{append_codepoint(124);} |
				"VerticalBar;" @{append_codepoint(8739);} |
				"VerticalLine;" @{append_codepoint(124);} |
				"VerticalSeparator;" @{append_codepoint(10072);} |
				"VerticalTilde;" @{append_codepoint(8768);} |
				"VeryThinSpace;" @{append_codepoint(8202);} |
				"Vfr;" @{append_codepoint(120089);} |
				"vfr;" @{append_codepoint(120115);} |
				"vltri;" @{append_codepoint(8882);} |
				"vnsub;" @{append_codepoint(8834);append_codepoint(8402);} |
				"vnsup;" @{append_codepoint(8835);append_codepoint(8402);} |
				"Vopf;" @{append_codepoint(120141);} |
				"vopf;" @{append_codepoint(120167);} |
				"vprop;" @{append_codepoint(8733);} |
				"vrtri;" @{append_codepoint(8883);} |
				"Vscr;" @{append_codepoint(119985);} |
				"vscr;" @{append_codepoint(120011);} |
				"vsubnE;" @{append_codepoint(10955);append_codepoint(65024);} |
				"vsubne;" @{append_codepoint(8842);append_codepoint(65024);} |
				"vsupnE;" @{append_codepoint(10956);append_codepoint(65024);} |
				"vsupne;" @{append_codepoint(8843);append_codepoint(65024);} |
				"Vvdash;" @{append_codepoint(8874);} |
				"vzigzag;" @{append_codepoint(10650);} |
				"Wcirc;" @{append_codepoint(372);} |
				"wcirc;" @{append_codepoint(373);} |
				"wedbar;" @{append_codepoint(10847);} |
				"Wedge;" @{append_codepoint(8896);} |
				"wedge;" @{append_codepoint(8743);} |
				"wedgeq;" @{append_codepoint(8793);} |
				"weierp;" @{append_codepoint(8472);} |
				"Wfr;" @{append_codepoint(120090);} |
				"wfr;" @{append_codepoint(120116);} |
				"Wopf;" @{append_codepoint(120142);} |
				"wopf;" @{append_codepoint(120168);} |
				"wp;" @{append_codepoint(8472);} |
				"wr;" @{append_codepoint(8768);} |
				"wreath;" @{append_codepoint(8768);} |
				"Wscr;" @{append_codepoint(119986);} |
				"wscr;" @{append_codepoint(120012);} |
				"xcap;" @{append_codepoint(8898);} |
				"xcirc;" @{append_codepoint(9711);} |
				"xcup;" @{append_codepoint(8899);} |
				"xdtri;" @{append_codepoint(9661);} |
				"Xfr;" @{append_codepoint(120091);} |
				"xfr;" @{append_codepoint(120117);} |
				"xhArr;" @{append_codepoint(10234);} |
				"xharr;" @{append_codepoint(10231);} |
				"Xi;" @{append_codepoint(926);} |
				"xi;" @{append_codepoint(958);} |
				"xlArr;" @{append_codepoint(10232);} |
				"xlarr;" @{append_codepoint(10229);} |
				"xmap;" @{append_codepoint(10236);} |
				"xnis;" @{append_codepoint(8955);} |
				"xodot;" @{append_codepoint(10752);} |
				"Xopf;" @{append_codepoint(120143);} |
				"xopf;" @{append_codepoint(120169);} |
				"xoplus;" @{append_codepoint(10753);} |
				"xotime;" @{append_codepoint(10754);} |
				"xrArr;" @{append_codepoint(10233);} |
				"xrarr;" @{append_codepoint(10230);} |
				"Xscr;" @{append_codepoint(119987);} |
				"xscr;" @{append_codepoint(120013);} |
				"xsqcup;" @{append_codepoint(10758);} |
				"xuplus;" @{append_codepoint(10756);} |
				"xutri;" @{append_codepoint(9651);} |
				"xvee;" @{append_codepoint(8897);} |
				"xwedge;" @{append_codepoint(8896);} |
				"Yacute;" @{append_codepoint(221);} |
				"yacute;" @{append_codepoint(253);} |
				"YAcy;" @{append_codepoint(1071);} |
				"yacy;" @{append_codepoint(1103);} |
				"Ycirc;" @{append_codepoint(374);} |
				"ycirc;" @{append_codepoint(375);} |
				"Ycy;" @{append_codepoint(1067);} |
				"ycy;" @{append_codepoint(1099);} |
				"yen;" @{append_codepoint(165);} |
				"Yfr;" @{append_codepoint(120092);} |
				"yfr;" @{append_codepoint(120118);} |
				"YIcy;" @{append_codepoint(1031);} |
				"yicy;" @{append_codepoint(1111);} |
				"Yopf;" @{append_codepoint(120144);} |
				"yopf;" @{append_codepoint(120170);} |
				"Yscr;" @{append_codepoint(119988);} |
				"yscr;" @{append_codepoint(120014);} |
				"YUcy;" @{append_codepoint(1070);} |
				"yucy;" @{append_codepoint(1102);} |
				"Yuml;" @{append_codepoint(376);} |
				"yuml;" @{append_codepoint(255);} |
				"Zacute;" @{append_codepoint(377);} |
				"zacute;" @{append_codepoint(378);} |
				"Zcaron;" @{append_codepoint(381);} |
				"zcaron;" @{append_codepoint(382);} |
				"Zcy;" @{append_codepoint(1047);} |
				"zcy;" @{append_codepoint(1079);} |
				"Zdot;" @{append_codepoint(379);} |
				"zdot;" @{append_codepoint(380);} |
				"zeetrf;" @{append_codepoint(8488);} |
				"ZeroWidthSpace;" @{append_codepoint(8203);} |
				"Zeta;" @{append_codepoint(918);} |
				"zeta;" @{append_codepoint(950);} |
				"Zfr;" @{append_codepoint(8488);} |
				"zfr;" @{append_codepoint(120119);} |
				"ZHcy;" @{append_codepoint(1046);} |
				"zhcy;" @{append_codepoint(1078);} |
				"zigrarr;" @{append_codepoint(8669);} |
				"Zopf;" @{append_codepoint(8484);} |
				"zopf;" @{append_codepoint(120171);} |
				"Zscr;" @{append_codepoint(119989);} |
				"zscr;" @{append_codepoint(120015);} |
				"zwj;" @{append_codepoint(8205);} |
				"zwnj;" @{append_codepoint(8204);} |
				'#x' [0-9a-fA-F]+ >entity_begin %entity_hex ';' |
		'#' [0-9]+ >entity_begin %entity_number ';'
	) @{fret;} @err(entity_error);
	
	entity = '&' @{fcall parse_entity;};
}%%
