# frozen_string_literal: true

spec_path = File.expand_path('../trenni.gemspec', Dir.pwd)
spec = Gem::Specification.load(spec_path)

require "rake/extensiontask"

unless RUBY_PLATFORM =~ /java/
	Rake::ExtensionTask.new("trenni") do |ext|
		ext.ext_dir = 'trenni'
		ext.lib_dir = '../lib/trenni'
	end
else
	task :compile do
		puts "Nothing to compile for this platform."
	end
end

task :default => :compile
